import numpy, functools
einsum = functools.partial(numpy.einsum, optimize=True)

def exp_nb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:34
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJK,JKL->IL'       , lam[5], amp[5])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    res +=     0.166667 * einsum('IJKL,JKLM->IM'     , lam[7], amp[7])
    res +=     0.500000 * einsum('IJKia,JKLai->IL'   , lam[6], amp[6])
    res +=     0.166667 * einsum('IJKLia,JKLMai->IM' , lam[8], amp[8])
    return res

def exp_xb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:36
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('I,IJ->J'           , lam[1], amp[3])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    res +=     0.500000 * einsum('IJ,IJK->K'         , lam[3], amp[5])
    res +=     1.000000 * einsum('Iia,IJai->J'       , lam[2], amp[4])
    res +=     0.166667 * einsum('IJK,IJKL->L'       , lam[5], amp[7])
    res +=     0.500000 * einsum('IJia,IJKai->K'     , lam[4], amp[6])
    res +=     0.166667 * einsum('IJKia,IJKLai->L'   , lam[6], amp[8])
    return res

def exp_na_ov_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:36
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:37
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    res +=     0.500000 * einsum('IJia,IJK->iaK'     , lam[4], amp[5])
    res +=     0.166667 * einsum('IJKia,IJKL->iaL'   , lam[6], amp[7])
    return res

def exp_na_vo_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:37
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=     0.166667 * einsum('IJK,IJKai->ai'     , lam[5], amp[6])
    res +=     0.041667 * einsum('IJKL,IJKLai->ai'   , lam[7], amp[8])
    return res

def exp_na_vo_xb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:38
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     0.500000 * einsum('IJ,IJKai->aiK'     , lam[3], amp[6])
    res +=     0.500000 * einsum('IJK,JKai->aiI'     , lam[5], amp[4])
    res +=     0.166667 * einsum('IJK,IJKLai->aiL'   , lam[5], amp[8])
    res +=     0.166667 * einsum('IJKL,JKLai->aiI'   , lam[7], amp[6])
    return res

def exp_na_oo_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:44
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    res +=    -0.166667 * einsum('IJKia,IJKaj->ij'   , lam[6], amp[6])
    res +=    -0.041667 * einsum('IJKLia,IJKLaj->ij' , lam[8], amp[8])
    return res

def exp_na_oo_xb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:53
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=    -0.500000 * einsum('IJia,IJKaj->ijK'   , lam[4], amp[6])
    res +=    -0.500000 * einsum('IJKia,JKaj->ijI'   , lam[6], amp[4])
    res +=    -0.166667 * einsum('IJKia,IJKLaj->ijL' , lam[6], amp[8])
    res +=    -0.166667 * einsum('IJKLia,JKLaj->ijI' , lam[8], amp[6])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=     0.500000 * einsum('IJ,IJK,ji->ijK'    , lam[3], amp[5], cc_obj.delta.oo)
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=     0.166667 * einsum('IJK,IJKL,ji->ijL'  , lam[5], amp[7], cc_obj.delta.oo)
    res +=     0.500000 * einsum('IJia,IJKai,kj->jkK', lam[4], amp[6], cc_obj.delta.oo)
    res +=     0.166667 * einsum('IJKia,IJKLai,kj->jkL', lam[6], amp[8], cc_obj.delta.oo)
    return res

def exp_na_vv_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:53
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    res +=     0.166667 * einsum('IJKia,IJKbi->ba'   , lam[6], amp[6])
    res +=     0.041667 * einsum('IJKLia,IJKLbi->ba' , lam[8], amp[8])
    return res

def exp_na_vv_xb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:53:54
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   218275365f71c5791e98226c4e3438e750974bb9

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    amp[5]: b+ b+ b+
    amp[6]: b+ b+ b+ a+_v a_o
    amp[7]: b+ b+ b+ b+
    amp[8]: b+ b+ b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v
    lam[5]: b b b
    lam[6]: b b b a+_o a_v
    lam[7]: b b b b
    lam[8]: b b b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     0.500000 * einsum('IJia,IJKbi->baK'   , lam[4], amp[6])
    res +=     0.500000 * einsum('IJKia,JKbi->baI'   , lam[6], amp[4])
    res +=     0.166667 * einsum('IJKia,IJKLbi->baL' , lam[6], amp[8])
    res +=     0.166667 * einsum('IJKLia,JKLbi->baI' , lam[8], amp[6])
    return res
