
def exp_nb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:31:33
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , cc_obj.xi, amp[1])
    res +=     1.000000 * einsum('I,J->IJ'           , cc_obj.xi, cc_obj.xi)
    res +=     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('I,J->IJ'           , lam[1], cc_obj.xi)
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    res +=     0.500000 * einsum('I,K,JK->IJ'        , cc_obj.xi, cc_obj.xi, amp[3])
    res +=     1.000000 * einsum('I,J,IK->JK'        , lam[1], cc_obj.xi, amp[3])
    res +=     0.500000 * einsum('I,K,JK->IJ'        , lam[1], cc_obj.xi, amp[3])
    res +=     1.000000 * einsum('ia,I,Jai->IJ'      , lam[0], cc_obj.xi, amp[2])
    res +=     1.000000 * einsum('Iia,J,IKai->JK'    , lam[2], cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('Iia,K,JKai->IJ'    , lam[2], cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('ia,I,K,JKai->IJ'   , lam[0], cc_obj.xi, cc_obj.xi, amp[4])
    return res

def exp_na_vo_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:31:36
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_vo_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:31:45
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     2.000000 * einsum('ia,I->iaI'         , lam[0], cc_obj.xi)
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    res +=     0.500000 * einsum('ia,J,IJ->iaI'      , lam[0], cc_obj.xi, amp[3])
    return res

def exp_na_ov_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:31:53
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('I,Iai->ai'         , cc_obj.xi, amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=     0.500000 * einsum('I,J,IJai->ai'      , lam[1], cc_obj.xi, amp[4])
    res +=     0.166667 * einsum('I,J,IJai->ai'      , cc_obj.xi, cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,IJbi->bj'  , lam[4], amp[0], amp[4])
    res +=    -0.500000 * einsum('IJia,bi,IJaj->bj'  , lam[4], amp[0], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,Jaj->bj'  , lam[4], amp[2], amp[2])
    res +=    -0.500000 * einsum('ia,aj,I,Ibi->bj'   , lam[0], amp[0], cc_obj.xi, amp[2])
    res +=    -0.500000 * einsum('ia,bi,I,Iaj->bj'   , lam[0], amp[0], cc_obj.xi, amp[2])
    res +=    -0.500000 * einsum('Iia,J,Iaj,Jbi->bj' , lam[2], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('Iia,J,Ibi,Jaj->bj' , lam[2], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('Iia,aj,J,IJbi->bj' , lam[2], amp[0], cc_obj.xi, amp[4])
    res +=    -0.500000 * einsum('Iia,bi,J,IJaj->bj' , lam[2], amp[0], cc_obj.xi, amp[4])
    res +=    -0.500000 * einsum('IJia,K,Iaj,JKbi->bj', lam[4], cc_obj.xi, amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,K,Ibi,JKaj->bj', lam[4], cc_obj.xi, amp[2], amp[4])
    res +=    -0.250000 * einsum('IJia,K,Kaj,IJbi->bj', lam[4], cc_obj.xi, amp[2], amp[4])
    res +=    -0.250000 * einsum('IJia,K,Kbi,IJaj->bj', lam[4], cc_obj.xi, amp[2], amp[4])
    return res

def exp_na_ov_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:32:49
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     2.000000 * einsum('ai,I->aiI'         , amp[0], cc_obj.xi)
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     0.500000 * einsum('J,IJai->aiI'       , cc_obj.xi, amp[4])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=     2.000000 * einsum('I,J,Iai->aiJ'      , lam[1], cc_obj.xi, amp[2])
    res +=     1.000000 * einsum('I,ai,IJ->aiJ'      , lam[1], amp[0], amp[3])
    res +=     0.500000 * einsum('I,J,Jai->aiI'      , lam[1], cc_obj.xi, amp[2])
    res +=     1.000000 * einsum('I,J,Jai->aiI'      , cc_obj.xi, cc_obj.xi, amp[2])
    res +=     0.500000 * einsum('J,I,Jai->aiI'      , cc_obj.xi, amp[1], amp[2])
    res +=     0.500000 * einsum('ai,J,IJ->aiI'      , amp[0], cc_obj.xi, amp[3])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=     0.500000 * einsum('IJ,K,IJai->aiK'    , lam[3], amp[1], amp[4])
    res +=     1.000000 * einsum('IJ,K,IJai->aiK'    , lam[3], cc_obj.xi, amp[4])
    res +=     1.000000 * einsum('IJ,Iai,JK->aiK'    , lam[3], amp[2], amp[3])
    res +=     0.500000 * einsum('IJ,K,JKai->aiI'    , lam[3], cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,IJbi->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,bi,IJaj->bjJ'  , lam[2], amp[0], amp[4])
    res +=     1.000000 * einsum('Iia,bj,IJai->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('IJia,aj,Jbi->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,bi,Jaj->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,Iaj,JKbi->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,JKaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('IJia,Ibj,JKai->bjK', lam[4], amp[2], amp[4])
    res +=     0.500000 * einsum('IJia,Kai,IJbj->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kaj,IJbi->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kbi,IJaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('I,J,K,IKai->aiJ'   , lam[1], cc_obj.xi, cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('I,K,J,IKai->aiJ'   , lam[1], cc_obj.xi, amp[1], amp[4])
    res +=     0.500000 * einsum('I,K,Iai,JK->aiJ'   , lam[1], cc_obj.xi, amp[2], amp[3])
    res +=     0.500000 * einsum('I,K,Kai,IJ->aiJ'   , lam[1], cc_obj.xi, amp[2], amp[3])
    res +=     0.166667 * einsum('I,J,K,JKai->aiI'   , lam[1], cc_obj.xi, cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -2.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], cc_obj.xi)
    res +=     0.500000 * einsum('ia,J,Iai,Jbj->bjI' , lam[0], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('ia,J,Ibi,Jaj->bjI' , lam[0], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('ia,J,Jbi,Iaj->bjI' , lam[0], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('ia,aj,J,IJbi->bjI' , lam[0], amp[0], cc_obj.xi, amp[4])
    res +=    -0.500000 * einsum('ia,bi,J,IJaj->bjI' , lam[0], amp[0], cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('ia,bj,J,IJai->bjI' , lam[0], amp[0], cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('IJ,L,IK,JLai->aiK' , lam[3], cc_obj.xi, amp[3], amp[4])
    res +=     0.250000 * einsum('IJ,L,KL,IJai->aiK' , lam[3], cc_obj.xi, amp[3], amp[4])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -2.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], cc_obj.xi, amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -2.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], cc_obj.xi, amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj,IJ->bjJ' , lam[2], amp[0], amp[0], amp[3])
    res +=    -0.500000 * einsum('Iia,aj,J,Jbi->bjI' , lam[2], amp[0], cc_obj.xi, amp[2])
    res +=    -0.500000 * einsum('Iia,bi,J,Jaj->bjI' , lam[2], amp[0], cc_obj.xi, amp[2])
    res +=    -0.500000 * einsum('Iia,K,Iaj,JKbi->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=    -0.500000 * einsum('Iia,K,Ibi,JKaj->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=     0.500000 * einsum('Iia,K,Ibj,JKai->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=     0.500000 * einsum('Iia,K,Jai,IKbj->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=    -0.500000 * einsum('Iia,K,Jaj,IKbi->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=    -0.500000 * einsum('Iia,K,Jbi,IKaj->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=    -0.500000 * einsum('Iia,K,Kaj,IJbi->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=    -0.500000 * einsum('Iia,K,Kbi,IJaj->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=     0.500000 * einsum('Iia,K,Kbj,IJai->bjJ', lam[2], cc_obj.xi, amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,K,Ibi,Jaj->bjK', lam[4], amp[1], amp[2], amp[2])
    res +=    -2.000000 * einsum('IJia,K,Ibi,Jaj->bjK', lam[4], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,K,IJbi->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,aj,K,IJbi->bjK', lam[4], amp[0], cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('IJia,aj,Ibi,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,bi,K,IJaj->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,bi,K,IJaj->bjK', lam[4], amp[0], cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('IJia,bi,Iaj,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,K,Jaj,Kbi->bjI', lam[4], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,K,Jbi,Kaj->bjI', lam[4], cc_obj.xi, amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,K,JKbi->bjI', lam[4], amp[0], cc_obj.xi, amp[4])
    res +=    -0.500000 * einsum('IJia,bi,K,JKaj->bjI', lam[4], amp[0], cc_obj.xi, amp[4])
    res +=    -0.250000 * einsum('IJia,L,IJaj,KLbi->bjK', lam[4], cc_obj.xi, amp[4], amp[4])
    res +=    -0.250000 * einsum('IJia,L,IJbi,KLaj->bjK', lam[4], cc_obj.xi, amp[4], amp[4])
    res +=     0.250000 * einsum('IJia,L,IJbj,KLai->bjK', lam[4], cc_obj.xi, amp[4], amp[4])
    res +=     0.500000 * einsum('IJia,L,IKai,JLbj->bjK', lam[4], cc_obj.xi, amp[4], amp[4])
    res +=    -0.500000 * einsum('IJia,L,IKbi,JLaj->bjK', lam[4], cc_obj.xi, amp[4], amp[4])
    res +=    -0.500000 * einsum('IJia,L,ILbi,JKaj->bjK', lam[4], cc_obj.xi, amp[4], amp[4])
    return res

def exp_na_oo_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:32:58
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    res +=    -0.500000 * einsum('ia,I,Iaj->ij'      , lam[0], cc_obj.xi, amp[2])
    res +=    -0.500000 * einsum('Iia,J,IJaj->ij'    , lam[2], cc_obj.xi, amp[4])
    res +=    -0.166667 * einsum('ia,I,J,IJaj->ij'   , lam[0], cc_obj.xi, cc_obj.xi, amp[4])
    return res

def exp_na_oo_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:33:44
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=     2.000000 * einsum('I,ji->ijI'         , cc_obj.xi, cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=    -2.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], cc_obj.xi)
    res +=     0.500000 * einsum('J,IJ,ji->ijI'      , cc_obj.xi, amp[3], cc_obj.delta.oo)
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('ia,J,IJaj->ijI'    , lam[0], cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    res +=    -2.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], cc_obj.xi, amp[2])
    res +=    -1.000000 * einsum('Iia,aj,IJ->ijJ'    , lam[2], amp[0], amp[3])
    res +=    -0.500000 * einsum('Iia,J,Jaj->ijI'    , lam[2], cc_obj.xi, amp[2])
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('IJia,K,IJaj->ijK'  , lam[4], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,K,IJaj->ijK'  , lam[4], cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('IJia,Iaj,JK->ijK'  , lam[4], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,K,JKaj->ijI'  , lam[4], cc_obj.xi, amp[4])
    res +=    -1.000000 * einsum('ia,I,J,Jaj->ijI'   , lam[0], cc_obj.xi, cc_obj.xi, amp[2])
    res +=    -0.500000 * einsum('ia,J,I,Jaj->ijI'   , lam[0], cc_obj.xi, amp[1], amp[2])
    res +=    -0.500000 * einsum('ia,aj,J,IJ->ijI'   , lam[0], amp[0], cc_obj.xi, amp[3])
    res +=     0.500000 * einsum('ia,J,IJai,kj->jkI' , lam[0], cc_obj.xi, amp[4], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,K,IKaj->ijJ' , lam[2], cc_obj.xi, cc_obj.xi, amp[4])
    res +=    -0.500000 * einsum('Iia,K,J,IKaj->ijJ' , lam[2], cc_obj.xi, amp[1], amp[4])
    res +=    -0.500000 * einsum('Iia,K,Iaj,JK->ijJ' , lam[2], cc_obj.xi, amp[2], amp[3])
    res +=    -0.500000 * einsum('Iia,K,Kaj,IJ->ijJ' , lam[2], cc_obj.xi, amp[2], amp[3])
    res +=    -0.166667 * einsum('Iia,J,K,JKaj->ijI' , lam[2], cc_obj.xi, cc_obj.xi, amp[4])
    res +=    -0.500000 * einsum('IJia,L,IK,JLaj->ijK', lam[4], cc_obj.xi, amp[3], amp[4])
    res +=    -0.250000 * einsum('IJia,L,KL,IJaj->ijK', lam[4], cc_obj.xi, amp[3], amp[4])
    return res

def exp_na_vv_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:33:48
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    res +=     0.500000 * einsum('ia,I,Ibi->ba'      , lam[0], cc_obj.xi, amp[2])
    res +=     0.500000 * einsum('Iia,J,IJbi->ba'    , lam[2], cc_obj.xi, amp[4])
    res +=     0.166667 * einsum('ia,I,J,IJbi->ba'   , lam[0], cc_obj.xi, cc_obj.xi, amp[4])
    return res

def exp_na_vv_xb_4(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 23:34:00
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   b1834fc535298bab10bffcea7f1f916f4a318f59

    amp[0]: a+_v a_o
    cc_obj.xi: b+
    cc_obj.xi: b
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     2.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], cc_obj.xi)
    res +=     0.500000 * einsum('ia,J,IJbi->baI'    , lam[0], cc_obj.xi, amp[4])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    res +=     2.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], cc_obj.xi, amp[2])
    res +=     1.000000 * einsum('Iia,bi,IJ->baJ'    , lam[2], amp[0], amp[3])
    res +=     0.500000 * einsum('Iia,J,Jbi->baI'    , lam[2], cc_obj.xi, amp[2])
    res +=     0.500000 * einsum('IJia,K,IJbi->baK'  , lam[4], amp[1], amp[4])
    res +=     1.000000 * einsum('IJia,K,IJbi->baK'  , lam[4], cc_obj.xi, amp[4])
    res +=     1.000000 * einsum('IJia,Ibi,JK->baK'  , lam[4], amp[2], amp[3])
    res +=     0.500000 * einsum('IJia,K,JKbi->baI'  , lam[4], cc_obj.xi, amp[4])
    res +=     1.000000 * einsum('ia,I,J,Jbi->baI'   , lam[0], cc_obj.xi, cc_obj.xi, amp[2])
    res +=     0.500000 * einsum('ia,J,I,Jbi->baI'   , lam[0], cc_obj.xi, amp[1], amp[2])
    res +=     0.500000 * einsum('ia,bi,J,IJ->baI'   , lam[0], amp[0], cc_obj.xi, amp[3])
    res +=     1.000000 * einsum('Iia,J,K,IKbi->baJ' , lam[2], cc_obj.xi, cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('Iia,K,J,IKbi->baJ' , lam[2], cc_obj.xi, amp[1], amp[4])
    res +=     0.500000 * einsum('Iia,K,Ibi,JK->baJ' , lam[2], cc_obj.xi, amp[2], amp[3])
    res +=     0.500000 * einsum('Iia,K,Kbi,IJ->baJ' , lam[2], cc_obj.xi, amp[2], amp[3])
    res +=     0.166667 * einsum('Iia,J,K,JKbi->baI' , lam[2], cc_obj.xi, cc_obj.xi, amp[4])
    res +=     0.500000 * einsum('IJia,L,IK,JLbi->baK', lam[4], cc_obj.xi, amp[3], amp[4])
    res +=     0.250000 * einsum('IJia,L,KL,IJbi->baK', lam[4], cc_obj.xi, amp[3], amp[4])
    return res
