import numpy, functools
einsum = functools.partial(numpy.einsum, optimize=True)

def exp_nb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:28
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    return res

def exp_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:30
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I->I'              , amp[1])
    res +=     1.000000 * einsum('I->I'              , lam[1])
    res +=     1.000000 * einsum('ia,Iai->I'         , lam[0], amp[2])
    return res

def exp_na_ov_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:31
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_ov_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:33
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    return res

def exp_na_vo_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:34
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ai->ai'            , amp[0])
    res +=     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    return res

def exp_na_vo_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:37
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('Iai->aiI'          , amp[2])
    res +=     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('ai,I->aiI'         , amp[0], amp[1])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    return res

def exp_na_oo_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:38
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ji->ij'            , cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    return res

def exp_na_oo_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:41
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=     1.000000 * einsum('I,ji->ijI'         , amp[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    return res

def exp_na_vv_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:42
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    return res

def exp_na_vv_xb_5(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 14:27:44
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   d36be63e8190b0979ac2fbce6742dbb8385f2dc3

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    return res
