import numpy, functools
einsum = functools.partial(numpy.einsum, optimize=True)

def res_ibra_0(cc_obj, amp):
    """
    Generated by utils.py at 2024-01-19 11:27:50
    Machine Info: Darwin 23.2.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   d9fa1416f9b6425ee2850274b4941fec6d0399df

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    res   :  a+_o a_v

    ih = 4, ibra = 0, len(tmp.terms) = 0
    """
    res  =     1.000000 * einsum('ai->ai'            , cc_obj.h1e.vo)
    res +=    -1.000000 * einsum('ji,aj->ai'         , cc_obj.h1e.oo, amp[0])
    res +=     1.000000 * einsum('ab,bi->ai'         , cc_obj.h1e.vv, amp[0])
    res +=    -1.000000 * einsum('jb,abji->ai'       , cc_obj.h1e.ov, amp[1])
    res +=    -1.000000 * einsum('jaib,bj->ai'       , cc_obj.h2e.ovov, amp[0])
    res +=     1.000000 * einsum('jabi,bj->ai'       , cc_obj.h2e.ovvo, amp[0])
    res +=     1.000000 * einsum('jkib,abkj->ai'     , cc_obj.h2e.ooov, amp[1])
    res +=    -1.000000 * einsum('jabc,cbji->ai'     , cc_obj.h2e.ovvv, amp[1])
    res +=    -1.000000 * einsum('jb,bi,aj->ai'      , cc_obj.h1e.ov, amp[0], amp[0])
    res +=    -1.000000 * einsum('jkib,aj,bk->ai'    , cc_obj.h2e.ooov, amp[0], amp[0])
    res +=     1.000000 * einsum('jkib,ak,bj->ai'    , cc_obj.h2e.ooov, amp[0], amp[0])
    res +=    -1.000000 * einsum('jabc,bi,cj->ai'    , cc_obj.h2e.ovvv, amp[0], amp[0])
    res +=     1.000000 * einsum('jabc,ci,bj->ai'    , cc_obj.h2e.ovvv, amp[0], amp[0])
    res +=    -1.000000 * einsum('jkbc,aj,cbki->ai'  , cc_obj.h2e.oovv, amp[0], amp[1])
    res +=    -1.000000 * einsum('jkbc,bj,acki->ai'  , cc_obj.h2e.oovv, amp[0], amp[1])
    res +=    -1.000000 * einsum('jkbc,ci,abkj->ai'  , cc_obj.h2e.oovv, amp[0], amp[1])
    res +=     1.000000 * einsum('jkbc,cj,abki->ai'  , cc_obj.h2e.oovv, amp[0], amp[1])
    res +=    -1.000000 * einsum('jkbc,bi,aj,ck->ai' , cc_obj.h2e.oovv, amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('jkbc,ci,aj,bk->ai' , cc_obj.h2e.oovv, amp[0], amp[0], amp[0])
    return res

def res_ibra_1(cc_obj, amp):
    """
    Generated by utils.py at 2024-01-19 11:29:18
    Machine Info: Darwin 23.2.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   d9fa1416f9b6425ee2850274b4941fec6d0399df

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    res   :  a+_o a+_o a_v a_v

    ih = 4, ibra = 1, len(tmp.terms) = 2
    """
    res  =    -1.000000 * einsum('abji->abij'        , cc_obj.h2e.vvoo)
    res +=     1.000000 * einsum('baji->abij'        , cc_obj.h2e.vvoo)
    res +=     1.000000 * einsum('ki,bakj->abij'     , cc_obj.h1e.oo, amp[1])
    res +=    -1.000000 * einsum('kj,baki->abij'     , cc_obj.h1e.oo, amp[1])
    res +=     1.000000 * einsum('ac,bcji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=    -1.000000 * einsum('bc,acji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=     1.000000 * einsum('kaij,bk->abij'     , cc_obj.h2e.ovoo, amp[0])
    res +=    -1.000000 * einsum('kaji,bk->abij'     , cc_obj.h2e.ovoo, amp[0])
    res +=    -1.000000 * einsum('kbij,ak->abij'     , cc_obj.h2e.ovoo, amp[0])
    res +=     1.000000 * einsum('kbji,ak->abij'     , cc_obj.h2e.ovoo, amp[0])
    res +=     1.000000 * einsum('abic,cj->abij'     , cc_obj.h2e.vvov, amp[0])
    res +=    -1.000000 * einsum('abjc,ci->abij'     , cc_obj.h2e.vvov, amp[0])
    res +=    -1.000000 * einsum('baic,cj->abij'     , cc_obj.h2e.vvov, amp[0])
    res +=     1.000000 * einsum('bajc,ci->abij'     , cc_obj.h2e.vvov, amp[0])
    res +=    -1.000000 * einsum('klji,balk->abij'   , cc_obj.h2e.oooo, amp[1])
    res +=     1.000000 * einsum('kaic,bckj->abij'   , cc_obj.h2e.ovov, amp[1])
    res +=    -1.000000 * einsum('kajc,bcki->abij'   , cc_obj.h2e.ovov, amp[1])
    res +=    -1.000000 * einsum('kaci,bckj->abij'   , cc_obj.h2e.ovvo, amp[1])
    res +=     1.000000 * einsum('kacj,bcki->abij'   , cc_obj.h2e.ovvo, amp[1])
    res +=    -1.000000 * einsum('kbic,ackj->abij'   , cc_obj.h2e.ovov, amp[1])
    res +=     1.000000 * einsum('kbjc,acki->abij'   , cc_obj.h2e.ovov, amp[1])
    res +=     1.000000 * einsum('kbci,ackj->abij'   , cc_obj.h2e.ovvo, amp[1])
    res +=    -1.000000 * einsum('kbcj,acki->abij'   , cc_obj.h2e.ovvo, amp[1])
    res +=    -1.000000 * einsum('bacd,dcji->abij'   , cc_obj.h2e.vvvv, amp[1])
    res +=    -1.000000 * einsum('kc,ak,bcji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,bk,acji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,ci,bakj->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kc,cj,baki->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('klji,bk,al->abij'  , cc_obj.h2e.oooo, amp[0], amp[0])
    res +=    -1.000000 * einsum('klji,bl,ak->abij'  , cc_obj.h2e.oooo, amp[0], amp[0])
    res +=     1.000000 * einsum('kaic,cj,bk->abij'  , cc_obj.h2e.ovov, amp[0], amp[0])
    res +=    -1.000000 * einsum('kajc,ci,bk->abij'  , cc_obj.h2e.ovov, amp[0], amp[0])
    res +=    -1.000000 * einsum('kaci,cj,bk->abij'  , cc_obj.h2e.ovvo, amp[0], amp[0])
    res +=     1.000000 * einsum('kacj,ci,bk->abij'  , cc_obj.h2e.ovvo, amp[0], amp[0])
    res +=    -1.000000 * einsum('kbic,cj,ak->abij'  , cc_obj.h2e.ovov, amp[0], amp[0])
    res +=     1.000000 * einsum('kbjc,ci,ak->abij'  , cc_obj.h2e.ovov, amp[0], amp[0])
    res +=     1.000000 * einsum('kbci,cj,ak->abij'  , cc_obj.h2e.ovvo, amp[0], amp[0])
    res +=    -1.000000 * einsum('kbcj,ci,ak->abij'  , cc_obj.h2e.ovvo, amp[0], amp[0])
    res +=    -1.000000 * einsum('bacd,ci,dj->abij'  , cc_obj.h2e.vvvv, amp[0], amp[0])
    res +=     1.000000 * einsum('bacd,di,cj->abij'  , cc_obj.h2e.vvvv, amp[0], amp[0])
    res +=     1.000000 * einsum('klic,ak,bclj->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('klic,al,bckj->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('klic,bk,aclj->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('klic,bl,ackj->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('klic,cj,balk->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('klic,ck,balj->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('klic,cl,bakj->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kljc,ak,bcli->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('kljc,al,bcki->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('kljc,bk,acli->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kljc,bl,acki->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kljc,ci,balk->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('kljc,ck,bali->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kljc,cl,baki->abij', cc_obj.h2e.ooov, amp[0], amp[1])
    res +=     1.000000 * einsum('kacd,bk,dcji->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('kacd,ci,bdkj->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kacd,cj,bdki->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('kacd,ck,bdji->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kacd,di,bckj->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('kacd,dj,bcki->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kacd,dk,bcji->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kbcd,ak,dcji->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kbcd,ci,adkj->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('kbcd,cj,adki->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kbcd,ck,adji->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('kbcd,di,ackj->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=    -1.000000 * einsum('kbcd,dj,acki->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('kbcd,dk,acji->abij', cc_obj.h2e.ovvv, amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,acki,bdlj->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=     1.000000 * einsum('klcd,adji,bclk->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=    -1.000000 * einsum('klcd,adki,bclj->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=    -1.000000 * einsum('klcd,baki,dclj->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=    -1.000000 * einsum('klcd,bcki,adlj->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=    -1.000000 * einsum('klcd,bdji,aclk->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=     1.000000 * einsum('klcd,bdki,aclj->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=     0.500000 * einsum('klcd,dcji,balk->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=    -1.000000 * einsum('klcd,dcki,balj->abij', cc_obj.h2e.oovv, amp[1], amp[1])
    res +=    -1.000000 * einsum('klic,cj,bk,al->abij', cc_obj.h2e.ooov, amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('klic,cj,bl,ak->abij', cc_obj.h2e.ooov, amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('kljc,ci,bk,al->abij', cc_obj.h2e.ooov, amp[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('kljc,ci,bl,ak->abij', cc_obj.h2e.ooov, amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('kacd,ci,dj,bk->abij', cc_obj.h2e.ovvv, amp[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('kacd,di,cj,bk->abij', cc_obj.h2e.ovvv, amp[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('kbcd,ci,dj,ak->abij', cc_obj.h2e.ovvv, amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('kbcd,di,cj,ak->abij', cc_obj.h2e.ovvv, amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('klcd,ak,cl,bdji->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,ak,dl,bcji->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,bk,al,dcji->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,bk,cl,adji->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,bk,dl,acji->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,ci,ak,bdlj->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,ci,bk,adlj->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,ci,dk,balj->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,cj,ak,bdli->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,cj,bk,adli->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,cj,dk,bali->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,di,ak,bclj->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,di,bk,aclj->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,di,cj,balk->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,di,ck,balj->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('klcd,dj,ak,bcli->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,dj,bk,acli->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,dj,ck,bali->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('klcd,ci,dj,bk,al->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[0], amp[0])
    res +=     1.000000 * einsum('klcd,di,cj,bk,al->abij', cc_obj.h2e.oovv, amp[0], amp[0], amp[0], amp[0])
    return res

