def ecorr(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:11:12
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
        """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 0, len(tmp.terms) = 0
    # ih = 1, ibra = 0, len(tmp.terms) = 2
    res  =     1.000000 * einsum('ia,ai->'           , cc_obj.h1e.ov, amp[0])
    res +=     0.500000 * einsum('iajb,baji->'       , cc_obj.chem.ovov, amp[1])

    # ih = 2, ibra = 0, len(tmp.terms) = 2
    res +=     0.500000 * einsum('iajb,ai,bj->'      , cc_obj.chem.ovov, amp[0], amp[0])
    res +=    -0.500000 * einsum('iajb,bi,aj->'      , cc_obj.chem.ovov, amp[0], amp[0])

    # ih = 3, ibra = 0, len(tmp.terms) = 0
    # ih = 4, ibra = 0, len(tmp.terms) = 0
    return res

def resd1(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:11:12
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    
    res   :  a+_o a_v
    """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 1, len(tmp.terms) = 1
    res  =     1.000000 * einsum('ai->ai'            , cc_obj.h1e.vo)

    # ih = 1, ibra = 1, len(tmp.terms) = 11
    res +=    -1.000000 * einsum('ji,aj->ai'         , cc_obj.h1e.oo, amp[0])
    res +=     1.000000 * einsum('ab,bi->ai'         , cc_obj.h1e.vv, amp[0])
    res +=    -1.000000 * einsum('jb,abji->ai'       , cc_obj.h1e.ov, amp[1])
    res +=    -0.500000 * einsum('jiab,bj->ai'       , cc_obj.chem.oovv, amp[0])
    res +=     0.500000 * einsum('jbai,bj->ai'       , cc_obj.chem.ovvo, amp[0])
    res +=     0.500000 * einsum('aijb,bj->ai'       , cc_obj.chem.voov, amp[0])
    res +=    -0.500000 * einsum('abji,bj->ai'       , cc_obj.chem.vvoo, amp[0])
    res +=     0.500000 * einsum('jikb,abkj->ai'     , cc_obj.chem.ooov, amp[1])
    res +=    -0.500000 * einsum('jbki,abkj->ai'     , cc_obj.chem.ovoo, amp[1])
    res +=    -0.500000 * einsum('jbac,cbji->ai'     , cc_obj.chem.ovvv, amp[1])
    res +=     0.500000 * einsum('abjc,cbji->ai'     , cc_obj.chem.vvov, amp[1])

    # ih = 2, ibra = 1, len(tmp.terms) = 17
    res +=    -1.000000 * einsum('jb,bi,aj->ai'      , cc_obj.h1e.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('jikb,aj,bk->ai'    , cc_obj.chem.ooov, amp[0], amp[0])
    res +=     0.500000 * einsum('jikb,ak,bj->ai'    , cc_obj.chem.ooov, amp[0], amp[0])
    res +=     0.500000 * einsum('jbki,aj,bk->ai'    , cc_obj.chem.ovoo, amp[0], amp[0])
    res +=    -0.500000 * einsum('jbki,ak,bj->ai'    , cc_obj.chem.ovoo, amp[0], amp[0])
    res +=    -0.500000 * einsum('jbac,bi,cj->ai'    , cc_obj.chem.ovvv, amp[0], amp[0])
    res +=     0.500000 * einsum('jbac,ci,bj->ai'    , cc_obj.chem.ovvv, amp[0], amp[0])
    res +=     0.500000 * einsum('abjc,bi,cj->ai'    , cc_obj.chem.vvov, amp[0], amp[0])
    res +=    -0.500000 * einsum('abjc,ci,bj->ai'    , cc_obj.chem.vvov, amp[0], amp[0])
    res +=    -0.500000 * einsum('jbkc,aj,cbki->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=     0.500000 * einsum('jbkc,ak,cbji->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=     0.500000 * einsum('jbkc,bi,ackj->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=    -0.500000 * einsum('jbkc,bj,acki->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=     0.500000 * einsum('jbkc,bk,acji->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=    -0.500000 * einsum('jbkc,ci,abkj->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=     0.500000 * einsum('jbkc,cj,abki->ai'  , cc_obj.chem.ovov, amp[0], amp[1])
    res +=    -0.500000 * einsum('jbkc,ck,abji->ai'  , cc_obj.chem.ovov, amp[0], amp[1])

    # ih = 3, ibra = 1, len(tmp.terms) = 4
    res +=    -0.500000 * einsum('jbkc,bi,aj,ck->ai' , cc_obj.chem.ovov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('jbkc,bi,ak,cj->ai' , cc_obj.chem.ovov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('jbkc,ci,aj,bk->ai' , cc_obj.chem.ovov, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('jbkc,ci,ak,bj->ai' , cc_obj.chem.ovov, amp[0], amp[0], amp[0])

    # ih = 4, ibra = 1, len(tmp.terms) = 0
    return res

def resd2(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:11:14
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    
    res   :  a+_o a+_o a_v a_v
    """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 2, len(tmp.terms) = 4
    res  =     0.500000 * einsum('aibj->abij'        , cc_obj.chem.vovo)
    res +=    -0.500000 * einsum('ajbi->abij'        , cc_obj.chem.vovo)
    res +=    -0.500000 * einsum('biaj->abij'        , cc_obj.chem.vovo)
    res +=     0.500000 * einsum('bjai->abij'        , cc_obj.chem.vovo)

    # ih = 1, ibra = 2, len(tmp.terms) = 40
    res +=     1.000000 * einsum('ki,bakj->abij'     , cc_obj.h1e.oo, amp[1])
    res +=    -1.000000 * einsum('kj,baki->abij'     , cc_obj.h1e.oo, amp[1])
    res +=     1.000000 * einsum('ac,bcji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=    -1.000000 * einsum('bc,acji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=     0.500000 * einsum('kiaj,bk->abij'     , cc_obj.chem.oovo, amp[0])
    res +=    -0.500000 * einsum('kibj,ak->abij'     , cc_obj.chem.oovo, amp[0])
    res +=    -0.500000 * einsum('kjai,bk->abij'     , cc_obj.chem.oovo, amp[0])
    res +=     0.500000 * einsum('kjbi,ak->abij'     , cc_obj.chem.oovo, amp[0])
    res +=    -0.500000 * einsum('aikj,bk->abij'     , cc_obj.chem.vooo, amp[0])
    res +=     0.500000 * einsum('aibc,cj->abij'     , cc_obj.chem.vovv, amp[0])
    res +=     0.500000 * einsum('ajki,bk->abij'     , cc_obj.chem.vooo, amp[0])
    res +=    -0.500000 * einsum('ajbc,ci->abij'     , cc_obj.chem.vovv, amp[0])
    res +=    -0.500000 * einsum('acbi,cj->abij'     , cc_obj.chem.vvvo, amp[0])
    res +=     0.500000 * einsum('acbj,ci->abij'     , cc_obj.chem.vvvo, amp[0])
    res +=     0.500000 * einsum('bikj,ak->abij'     , cc_obj.chem.vooo, amp[0])
    res +=    -0.500000 * einsum('biac,cj->abij'     , cc_obj.chem.vovv, amp[0])
    res +=    -0.500000 * einsum('bjki,ak->abij'     , cc_obj.chem.vooo, amp[0])
    res +=     0.500000 * einsum('bjac,ci->abij'     , cc_obj.chem.vovv, amp[0])
    res +=     0.500000 * einsum('bcai,cj->abij'     , cc_obj.chem.vvvo, amp[0])
    res +=    -0.500000 * einsum('bcaj,ci->abij'     , cc_obj.chem.vvvo, amp[0])
    res +=     0.500000 * einsum('kilj,balk->abij'   , cc_obj.chem.oooo, amp[1])
    res +=     0.500000 * einsum('kiac,bckj->abij'   , cc_obj.chem.oovv, amp[1])
    res +=    -0.500000 * einsum('kibc,ackj->abij'   , cc_obj.chem.oovv, amp[1])
    res +=    -0.500000 * einsum('kjli,balk->abij'   , cc_obj.chem.oooo, amp[1])
    res +=    -0.500000 * einsum('kjac,bcki->abij'   , cc_obj.chem.oovv, amp[1])
    res +=     0.500000 * einsum('kjbc,acki->abij'   , cc_obj.chem.oovv, amp[1])
    res +=    -0.500000 * einsum('kcai,bckj->abij'   , cc_obj.chem.ovvo, amp[1])
    res +=     0.500000 * einsum('kcaj,bcki->abij'   , cc_obj.chem.ovvo, amp[1])
    res +=     0.500000 * einsum('kcbi,ackj->abij'   , cc_obj.chem.ovvo, amp[1])
    res +=    -0.500000 * einsum('kcbj,acki->abij'   , cc_obj.chem.ovvo, amp[1])
    res +=    -0.500000 * einsum('aikc,bckj->abij'   , cc_obj.chem.voov, amp[1])
    res +=     0.500000 * einsum('ajkc,bcki->abij'   , cc_obj.chem.voov, amp[1])
    res +=     0.500000 * einsum('acki,bckj->abij'   , cc_obj.chem.vvoo, amp[1])
    res +=    -0.500000 * einsum('ackj,bcki->abij'   , cc_obj.chem.vvoo, amp[1])
    res +=     0.500000 * einsum('acbd,dcji->abij'   , cc_obj.chem.vvvv, amp[1])
    res +=     0.500000 * einsum('bikc,ackj->abij'   , cc_obj.chem.voov, amp[1])
    res +=    -0.500000 * einsum('bjkc,acki->abij'   , cc_obj.chem.voov, amp[1])
    res +=    -0.500000 * einsum('bcki,ackj->abij'   , cc_obj.chem.vvoo, amp[1])
    res +=     0.500000 * einsum('bckj,acki->abij'   , cc_obj.chem.vvoo, amp[1])
    res +=    -0.500000 * einsum('bcad,dcji->abij'   , cc_obj.chem.vvvv, amp[1])

    # ih = 2, ibra = 2, len(tmp.terms) = 101
    res +=    -1.000000 * einsum('kc,ak,bcji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,bk,acji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,ci,bakj->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kc,cj,baki->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kilj,bk,al->abij'  , cc_obj.chem.oooo, amp[0], amp[0])
    res +=     0.500000 * einsum('kilj,bl,ak->abij'  , cc_obj.chem.oooo, amp[0], amp[0])
    res +=     0.500000 * einsum('kiac,cj,bk->abij'  , cc_obj.chem.oovv, amp[0], amp[0])
    res +=    -0.500000 * einsum('kibc,cj,ak->abij'  , cc_obj.chem.oovv, amp[0], amp[0])
    res +=     0.500000 * einsum('kjli,bk,al->abij'  , cc_obj.chem.oooo, amp[0], amp[0])
    res +=    -0.500000 * einsum('kjli,bl,ak->abij'  , cc_obj.chem.oooo, amp[0], amp[0])
    res +=    -0.500000 * einsum('kjac,ci,bk->abij'  , cc_obj.chem.oovv, amp[0], amp[0])
    res +=     0.500000 * einsum('kjbc,ci,ak->abij'  , cc_obj.chem.oovv, amp[0], amp[0])
    res +=    -0.500000 * einsum('kcai,cj,bk->abij'  , cc_obj.chem.ovvo, amp[0], amp[0])
    res +=     0.500000 * einsum('kcaj,ci,bk->abij'  , cc_obj.chem.ovvo, amp[0], amp[0])
    res +=     0.500000 * einsum('kcbi,cj,ak->abij'  , cc_obj.chem.ovvo, amp[0], amp[0])
    res +=    -0.500000 * einsum('kcbj,ci,ak->abij'  , cc_obj.chem.ovvo, amp[0], amp[0])
    res +=    -0.500000 * einsum('aikc,cj,bk->abij'  , cc_obj.chem.voov, amp[0], amp[0])
    res +=     0.500000 * einsum('ajkc,ci,bk->abij'  , cc_obj.chem.voov, amp[0], amp[0])
    res +=     0.500000 * einsum('acki,cj,bk->abij'  , cc_obj.chem.vvoo, amp[0], amp[0])
    res +=    -0.500000 * einsum('ackj,ci,bk->abij'  , cc_obj.chem.vvoo, amp[0], amp[0])
    res +=     0.500000 * einsum('acbd,ci,dj->abij'  , cc_obj.chem.vvvv, amp[0], amp[0])
    res +=    -0.500000 * einsum('acbd,di,cj->abij'  , cc_obj.chem.vvvv, amp[0], amp[0])
    res +=     0.500000 * einsum('bikc,cj,ak->abij'  , cc_obj.chem.voov, amp[0], amp[0])
    res +=    -0.500000 * einsum('bjkc,ci,ak->abij'  , cc_obj.chem.voov, amp[0], amp[0])
    res +=    -0.500000 * einsum('bcki,cj,ak->abij'  , cc_obj.chem.vvoo, amp[0], amp[0])
    res +=     0.500000 * einsum('bckj,ci,ak->abij'  , cc_obj.chem.vvoo, amp[0], amp[0])
    res +=    -0.500000 * einsum('bcad,ci,dj->abij'  , cc_obj.chem.vvvv, amp[0], amp[0])
    res +=     0.500000 * einsum('bcad,di,cj->abij'  , cc_obj.chem.vvvv, amp[0], amp[0])
    res +=     0.500000 * einsum('kilc,ak,bclj->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kilc,al,bckj->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kilc,bk,aclj->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=     0.500000 * einsum('kilc,bl,ackj->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=     0.500000 * einsum('kilc,cj,balk->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kilc,ck,balj->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=     0.500000 * einsum('kilc,cl,bakj->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kjlc,ak,bcli->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=     0.500000 * einsum('kjlc,al,bcki->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=     0.500000 * einsum('kjlc,bk,acli->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kjlc,bl,acki->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kjlc,ci,balk->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=     0.500000 * einsum('kjlc,ck,bali->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kjlc,cl,baki->abij', cc_obj.chem.ooov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcli,ak,bclj->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kcli,al,bckj->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kcli,bk,aclj->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcli,bl,ackj->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcli,cj,balk->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kcli,ck,balj->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcli,cl,bakj->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kclj,ak,bcli->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=    -0.500000 * einsum('kclj,al,bcki->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=    -0.500000 * einsum('kclj,bk,acli->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kclj,bl,acki->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kclj,ci,balk->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=    -0.500000 * einsum('kclj,ck,bali->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kclj,cl,baki->abij', cc_obj.chem.ovoo, amp[0], amp[1])
    res +=     0.500000 * einsum('kcad,bk,dcji->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=     0.500000 * einsum('kcad,ci,bdkj->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcad,cj,bdki->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=     0.500000 * einsum('kcad,ck,bdji->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcad,di,bckj->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=     0.500000 * einsum('kcad,dj,bcki->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcad,dk,bcji->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcbd,ak,dcji->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcbd,ci,adkj->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=     0.500000 * einsum('kcbd,cj,adki->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcbd,ck,adji->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=     0.500000 * einsum('kcbd,di,ackj->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcbd,dj,acki->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=     0.500000 * einsum('kcbd,dk,acji->abij', cc_obj.chem.ovvv, amp[0], amp[1])
    res +=    -0.500000 * einsum('ackd,bk,dcji->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('ackd,ci,bdkj->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('ackd,cj,bdki->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('ackd,ck,bdji->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('ackd,di,bckj->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('ackd,dj,bcki->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('ackd,dk,bcji->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('bckd,ak,dcji->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('bckd,ci,adkj->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('bckd,cj,adki->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('bckd,ck,adji->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('bckd,di,ackj->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=     0.500000 * einsum('bckd,dj,acki->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('bckd,dk,acji->abij', cc_obj.chem.vvov, amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,acji,bdlk->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,acki,bdlj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,acli,bdkj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,adji,bclk->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,adki,bclj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,adli,bckj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,baki,dclj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,bali,dckj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,bcji,adlk->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,bcki,adlj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,bcli,adkj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,bdji,aclk->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,bdki,aclj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,bdli,ackj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,dcji,balk->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=    -0.500000 * einsum('kcld,dcki,balj->abij', cc_obj.chem.ovov, amp[1], amp[1])
    res +=     0.500000 * einsum('kcld,dcli,bakj->abij', cc_obj.chem.ovov, amp[1], amp[1])

    # ih = 3, ibra = 2, len(tmp.terms) = 52
    res +=    -0.500000 * einsum('kilc,cj,bk,al->abij', cc_obj.chem.ooov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kilc,cj,bl,ak->abij', cc_obj.chem.ooov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kjlc,ci,bk,al->abij', cc_obj.chem.ooov, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('kjlc,ci,bl,ak->abij', cc_obj.chem.ooov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kcli,cj,bk,al->abij', cc_obj.chem.ovoo, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('kcli,cj,bl,ak->abij', cc_obj.chem.ovoo, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('kclj,ci,bk,al->abij', cc_obj.chem.ovoo, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kclj,ci,bl,ak->abij', cc_obj.chem.ovoo, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kcad,ci,dj,bk->abij', cc_obj.chem.ovvv, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('kcad,di,cj,bk->abij', cc_obj.chem.ovvv, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('kcbd,ci,dj,ak->abij', cc_obj.chem.ovvv, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kcbd,di,cj,ak->abij', cc_obj.chem.ovvv, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('ackd,ci,dj,bk->abij', cc_obj.chem.vvov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('ackd,di,cj,bk->abij', cc_obj.chem.vvov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('bckd,ci,dj,ak->abij', cc_obj.chem.vvov, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('bckd,di,cj,ak->abij', cc_obj.chem.vvov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kcld,ak,cl,bdji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,ak,dl,bcji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,al,ck,bdji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,al,dk,bcji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,bk,al,dcji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,bk,cl,adji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,bk,dl,acji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,bl,ak,dcji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,bl,ck,adji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,bl,dk,acji->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,ci,ak,bdlj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,ci,al,bdkj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,ci,bk,adlj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,ci,bl,adkj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,ci,dj,balk->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,ci,dk,balj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,ci,dl,bakj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,cj,ak,bdli->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,cj,al,bdki->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,cj,bk,adli->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,cj,bl,adki->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,cj,dk,bali->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,cj,dl,baki->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,di,ak,bclj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,di,al,bckj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,di,bk,aclj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,di,bl,ackj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,di,cj,balk->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,di,ck,balj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,di,cl,bakj->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,dj,ak,bcli->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,dj,al,bcki->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,dj,bk,acli->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,dj,bl,acki->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('kcld,dj,ck,bali->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('kcld,dj,cl,baki->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[1])

    # ih = 4, ibra = 2, len(tmp.terms) = 4
    res +=    -0.500000 * einsum('kcld,ci,dj,bk,al->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kcld,ci,dj,bl,ak->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('kcld,di,cj,bk,al->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('kcld,di,cj,bl,ak->abij', cc_obj.chem.ovov, amp[0], amp[0], amp[0], amp[0])

    return res