def ecorr(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:15:49
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
        """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 0, len(tmp.terms) = 0
    # ih = 1, ibra = 0, len(tmp.terms) = 2
    res  =     1.000000 * einsum('ia,ai->'           , cc_obj.h1e.ov, amp[0])
    res +=     0.500000 * einsum('Pi,Pa,Qj,Qb,PQ,baji->', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])

    # ih = 2, ibra = 0, len(tmp.terms) = 2
    res +=     0.500000 * einsum('Pi,Pa,Qj,Qb,PQ,ai,bj->', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pi,Pa,Qj,Qb,PQ,bi,aj->', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])

    # ih = 3, ibra = 0, len(tmp.terms) = 0
    # ih = 4, ibra = 0, len(tmp.terms) = 0
    return res

def resd1(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:15:49
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    
    res   :  a+_o a_v
    """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 1, len(tmp.terms) = 1
    res  =     1.000000 * einsum('ai->ai'            , cc_obj.h1e.vo)

    # ih = 1, ibra = 1, len(tmp.terms) = 11
    res +=    -1.000000 * einsum('ji,aj->ai'         , cc_obj.h1e.oo, amp[0])
    res +=     1.000000 * einsum('ab,bi->ai'         , cc_obj.h1e.vv, amp[0])
    res +=    -1.000000 * einsum('jb,abji->ai'       , cc_obj.h1e.ov, amp[1])
    res +=     0.500000 * einsum('Pj,Pi,Qa,Qb,PQ,bj->ai', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pj,Pb,Qa,Qi,PQ,bj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pa,Pi,Qj,Qb,PQ,bj->ai', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pa,Pb,Qj,Qi,PQ,bj->ai', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pj,Pi,Qk,Qb,PQ,abkj->ai', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qi,PQ,abkj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pj,Pb,Qa,Qc,PQ,cbji->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pa,Pb,Qj,Qc,PQ,cbji->ai', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])

    # ih = 2, ibra = 1, len(tmp.terms) = 17
    res +=    -1.000000 * einsum('jb,bi,aj->ai'      , cc_obj.h1e.ov, amp[0], amp[0])
    res +=     0.500000 * einsum('Pj,Pi,Qk,Qb,PQ,aj,bk->ai', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pj,Pi,Qk,Qb,PQ,ak,bj->ai', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qi,PQ,aj,bk->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qi,PQ,ak,bj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pj,Pb,Qa,Qc,PQ,bi,cj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pj,Pb,Qa,Qc,PQ,ci,bj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pa,Pb,Qj,Qc,PQ,bi,cj->ai', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pa,Pb,Qj,Qc,PQ,ci,bj->ai', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,aj,cbki->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,ak,cbji->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,bi,ackj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,bj,acki->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,bk,acji->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,ci,abkj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,cj,abki->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,ck,abji->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])

    # ih = 3, ibra = 1, len(tmp.terms) = 4
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,bi,aj,ck->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,bi,ak,cj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,ci,aj,bk->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pj,Pb,Qk,Qc,PQ,ci,ak,bj->ai', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])

    # ih = 4, ibra = 1, len(tmp.terms) = 0
    return res

def resd2(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:15:51
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    
    res   :  a+_o a+_o a_v a_v
    """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 2, len(tmp.terms) = 4
    res  =     0.500000 * einsum('Pa,Pi,Qb,Qj,PQ->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz)
    res +=    -0.500000 * einsum('Pa,Pj,Qb,Qi,PQ->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz)
    res +=    -0.500000 * einsum('Pb,Pi,Qa,Qj,PQ->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz)
    res +=     0.500000 * einsum('Pb,Pj,Qa,Qi,PQ->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz)

    # ih = 1, ibra = 2, len(tmp.terms) = 40
    res +=     1.000000 * einsum('ki,bakj->abij'     , cc_obj.h1e.oo, amp[1])
    res +=    -1.000000 * einsum('kj,baki->abij'     , cc_obj.h1e.oo, amp[1])
    res +=     1.000000 * einsum('ac,bcji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=    -1.000000 * einsum('bc,acji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=    -0.500000 * einsum('Pk,Pi,Qa,Qj,PQ,bk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pk,Pi,Qb,Qj,PQ,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pk,Pj,Qa,Qi,PQ,bk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pk,Pj,Qb,Qi,PQ,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pa,Pi,Qk,Qj,PQ,bk->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pa,Pi,Qb,Qc,PQ,cj->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pa,Pj,Qk,Qi,PQ,bk->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pa,Pj,Qb,Qc,PQ,ci->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pa,Pc,Qb,Qi,PQ,cj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pa,Pc,Qb,Qj,PQ,ci->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pb,Pi,Qk,Qj,PQ,ak->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pb,Pi,Qa,Qc,PQ,cj->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pb,Pj,Qk,Qi,PQ,ak->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pb,Pj,Qa,Qc,PQ,ci->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pb,Pc,Qa,Qi,PQ,cj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=    -0.500000 * einsum('Pb,Pc,Qa,Qj,PQ,ci->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0])
    res +=     0.500000 * einsum('Pk,Pi,Ql,Qj,PQ,balk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pk,Pi,Qa,Qc,PQ,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pk,Pi,Qb,Qc,PQ,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pk,Pj,Ql,Qi,PQ,balk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pk,Pj,Qa,Qc,PQ,bcki->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pk,Pj,Qb,Qc,PQ,acki->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qi,PQ,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qa,Qj,PQ,bcki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qi,PQ,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qb,Qj,PQ,acki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pa,Pi,Qk,Qc,PQ,bckj->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pa,Pj,Qk,Qc,PQ,bcki->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qi,PQ,bckj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pa,Pc,Qk,Qj,PQ,bcki->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pa,Pc,Qb,Qd,PQ,dcji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pb,Pi,Qk,Qc,PQ,ackj->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pb,Pj,Qk,Qc,PQ,acki->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qi,PQ,ackj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pb,Pc,Qk,Qj,PQ,acki->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[1])
    res +=    -0.500000 * einsum('Pb,Pc,Qa,Qd,PQ,dcji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[1])

    # ih = 2, ibra = 2, len(tmp.terms) = 101
    res +=    -1.000000 * einsum('kc,ak,bcji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,bk,acji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,ci,bakj->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kc,cj,baki->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pi,Ql,Qj,PQ,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pi,Ql,Qj,PQ,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pi,Qa,Qc,PQ,cj,bk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pi,Qb,Qc,PQ,cj,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pj,Ql,Qi,PQ,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pj,Ql,Qi,PQ,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pj,Qa,Qc,PQ,ci,bk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pj,Qb,Qc,PQ,ci,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qi,PQ,cj,bk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Qa,Qj,PQ,ci,bk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qi,PQ,cj,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Qb,Qj,PQ,ci,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pa,Pi,Qk,Qc,PQ,cj,bk->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pa,Pj,Qk,Qc,PQ,ci,bk->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qi,PQ,cj,bk->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pa,Pc,Qk,Qj,PQ,ci,bk->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pa,Pc,Qb,Qd,PQ,ci,dj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pa,Pc,Qb,Qd,PQ,di,cj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pb,Pi,Qk,Qc,PQ,cj,ak->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pb,Pj,Qk,Qc,PQ,ci,ak->abij', cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qi,PQ,cj,ak->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pb,Pc,Qk,Qj,PQ,ci,ak->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pb,Pc,Qa,Qd,PQ,ci,dj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=     0.500000 * einsum('Pb,Pc,Qa,Qd,PQ,di,cj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,ak,bclj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,al,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,bk,aclj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,bl,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,cj,balk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,ck,balj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,cl,bakj->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,ak,bcli->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,al,bcki->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,bk,acli->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,bl,acki->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,ci,balk->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,ck,bali->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,cl,baki->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,ak,bclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,al,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,bk,aclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,bl,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,cj,balk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,ck,balj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,cl,bakj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,ak,bcli->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,al,bcki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,bk,acli->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,bl,acki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,ci,balk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,ck,bali->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,cl,baki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,bk,dcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,ci,bdkj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,cj,bdki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,ck,bdji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,di,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,dj,bcki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,dk,bcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,ak,dcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,ci,adkj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,cj,adki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,ck,adji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,di,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,dj,acki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,dk,acji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,bk,dcji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,ci,bdkj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,cj,bdki->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,ck,bdji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,di,bckj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,dj,bcki->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,dk,bcji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,ak,dcji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,ci,adkj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,cj,adki->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,ck,adji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,di,ackj->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,dj,acki->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,dk,acji->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,acji,bdlk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,acki,bdlj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,acli,bdkj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,adji,bclk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,adki,bclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,adli,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,baki,dclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bali,dckj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bcji,adlk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bcki,adlj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bcli,adkj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bdji,aclk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bdki,aclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bdli,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dcji,balk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dcki,balj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dcli,bakj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[1], amp[1])

    # ih = 3, ibra = 2, len(tmp.terms) = 52
    res +=     0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,cj,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pi,Ql,Qc,PQ,cj,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,ci,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pj,Ql,Qc,PQ,ci,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,cj,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qi,PQ,cj,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,ci,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qj,PQ,ci,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.o, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,ci,dj,bk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Qa,Qd,PQ,di,cj,bk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,ci,dj,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Qb,Qd,PQ,di,cj,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,ci,dj,bk->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pa,Pc,Qk,Qd,PQ,di,cj,bk->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,ci,dj,ak->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pb,Pc,Qk,Qd,PQ,di,cj,ak->abij', cc_obj.thcx.v, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ak,cl,bdji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ak,dl,bcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,al,ck,bdji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,al,dk,bcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bk,al,dcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bk,cl,adji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bk,dl,acji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bl,ak,dcji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bl,ck,adji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,bl,dk,acji->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,ak,bdlj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,al,bdkj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,bk,adlj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,bl,adkj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,dj,balk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,dk,balj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,dl,bakj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,cj,ak,bdli->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,cj,al,bdki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,cj,bk,adli->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,cj,bl,adki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,cj,dk,bali->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,cj,dl,baki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,ak,bclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,al,bckj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,bk,aclj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,bl,ackj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,cj,balk->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,ck,balj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,cl,bakj->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dj,ak,bcli->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dj,al,bcki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dj,bk,acli->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dj,bl,acki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dj,ck,bali->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,dj,cl,baki->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[1])

    # ih = 4, ibra = 2, len(tmp.terms) = 4
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,dj,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,ci,dj,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,cj,bk,al->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pk,Pc,Ql,Qd,PQ,di,cj,bl,ak->abij', cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcx.o, cc_obj.thcx.v, cc_obj.thcz, amp[0], amp[0], amp[0], amp[0])

    return res