def ecorr(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:13:19
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
        """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 0, len(tmp.terms) = 0
    # ih = 1, ibra = 0, len(tmp.terms) = 2
    res  =     1.000000 * einsum('ia,ai->'           , cc_obj.h1e.ov, amp[0])
    res +=     0.500000 * einsum('Pia,Pjb,baji->'    , cc_obj.chol.ov, cc_obj.chol.ov, amp[1])

    # ih = 2, ibra = 0, len(tmp.terms) = 2
    res +=     0.500000 * einsum('Pia,Pjb,ai,bj->'   , cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pia,Pjb,bi,aj->'   , cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0])

    # ih = 3, ibra = 0, len(tmp.terms) = 0
    # ih = 4, ibra = 0, len(tmp.terms) = 0
    return res

def resd1(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:13:19
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    
    res   :  a+_o a_v
    """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 1, len(tmp.terms) = 1
    res  =     1.000000 * einsum('ai->ai'            , cc_obj.h1e.vo)

    # ih = 1, ibra = 1, len(tmp.terms) = 11
    res +=    -1.000000 * einsum('ji,aj->ai'         , cc_obj.h1e.oo, amp[0])
    res +=     1.000000 * einsum('ab,bi->ai'         , cc_obj.h1e.vv, amp[0])
    res +=    -1.000000 * einsum('jb,abji->ai'       , cc_obj.h1e.ov, amp[1])
    res +=    -0.500000 * einsum('Pji,Pab,bj->ai'    , cc_obj.chol.oo, cc_obj.chol.vv, amp[0])
    res +=     0.500000 * einsum('Pjb,Pai,bj->ai'    , cc_obj.chol.ov, cc_obj.chol.vo, amp[0])
    res +=     0.500000 * einsum('Pai,Pjb,bj->ai'    , cc_obj.chol.vo, cc_obj.chol.ov, amp[0])
    res +=    -0.500000 * einsum('Pab,Pji,bj->ai'    , cc_obj.chol.vv, cc_obj.chol.oo, amp[0])
    res +=     0.500000 * einsum('Pji,Pkb,abkj->ai'  , cc_obj.chol.oo, cc_obj.chol.ov, amp[1])
    res +=    -0.500000 * einsum('Pjb,Pki,abkj->ai'  , cc_obj.chol.ov, cc_obj.chol.oo, amp[1])
    res +=    -0.500000 * einsum('Pjb,Pac,cbji->ai'  , cc_obj.chol.ov, cc_obj.chol.vv, amp[1])
    res +=     0.500000 * einsum('Pab,Pjc,cbji->ai'  , cc_obj.chol.vv, cc_obj.chol.ov, amp[1])

    # ih = 2, ibra = 1, len(tmp.terms) = 17
    res +=    -1.000000 * einsum('jb,bi,aj->ai'      , cc_obj.h1e.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pji,Pkb,aj,bk->ai' , cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[0])
    res +=     0.500000 * einsum('Pji,Pkb,ak,bj->ai' , cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[0])
    res +=     0.500000 * einsum('Pjb,Pki,aj,bk->ai' , cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pjb,Pki,ak,bj->ai' , cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pjb,Pac,bi,cj->ai' , cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pjb,Pac,ci,bj->ai' , cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pab,Pjc,bi,cj->ai' , cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pab,Pjc,ci,bj->ai' , cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pjb,Pkc,aj,cbki->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pjb,Pkc,ak,cbji->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pjb,Pkc,bi,ackj->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pjb,Pkc,bj,acki->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pjb,Pkc,bk,acji->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pjb,Pkc,ci,abkj->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pjb,Pkc,cj,abki->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pjb,Pkc,ck,abji->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[1])

    # ih = 3, ibra = 1, len(tmp.terms) = 4
    res +=    -0.500000 * einsum('Pjb,Pkc,bi,aj,ck->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pjb,Pkc,bi,ak,cj->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pjb,Pkc,ci,aj,bk->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pjb,Pkc,ci,ak,bj->ai', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0])

    # ih = 4, ibra = 1, len(tmp.terms) = 0
    return res

def resd2(cc_obj, amp):
    """
    Generated by gen-gccsd-equations.py at 2024-01-31 15:13:21
    Machine Info: Darwin 23.2.0
    Hostname:     X66TT4T9M9
    Git Branch:   pauling
    Git Commit:   0890d06c932191307802f5ed54fe28094d74543c

    amp[0]: a+_v a_o
    amp[1]: a+_v a+_v a_o a_o
    
    res   :  a+_o a+_o a_v a_v
    """

    einsum = getattr(cc_obj, "einsum", None)
    assert einsum is not None, "einsum is not defined in cc_obj"

    # ih = 0, ibra = 2, len(tmp.terms) = 4
    res  =     0.500000 * einsum('Pai,Pbj->abij'     , cc_obj.chol.vo, cc_obj.chol.vo)
    res +=    -0.500000 * einsum('Paj,Pbi->abij'     , cc_obj.chol.vo, cc_obj.chol.vo)
    res +=    -0.500000 * einsum('Pbi,Paj->abij'     , cc_obj.chol.vo, cc_obj.chol.vo)
    res +=     0.500000 * einsum('Pbj,Pai->abij'     , cc_obj.chol.vo, cc_obj.chol.vo)

    # ih = 1, ibra = 2, len(tmp.terms) = 40
    res +=     1.000000 * einsum('ki,bakj->abij'     , cc_obj.h1e.oo, amp[1])
    res +=    -1.000000 * einsum('kj,baki->abij'     , cc_obj.h1e.oo, amp[1])
    res +=     1.000000 * einsum('ac,bcji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=    -1.000000 * einsum('bc,acji->abij'     , cc_obj.h1e.vv, amp[1])
    res +=     0.500000 * einsum('Pki,Paj,bk->abij'  , cc_obj.chol.oo, cc_obj.chol.vo, amp[0])
    res +=    -0.500000 * einsum('Pki,Pbj,ak->abij'  , cc_obj.chol.oo, cc_obj.chol.vo, amp[0])
    res +=    -0.500000 * einsum('Pkj,Pai,bk->abij'  , cc_obj.chol.oo, cc_obj.chol.vo, amp[0])
    res +=     0.500000 * einsum('Pkj,Pbi,ak->abij'  , cc_obj.chol.oo, cc_obj.chol.vo, amp[0])
    res +=    -0.500000 * einsum('Pai,Pkj,bk->abij'  , cc_obj.chol.vo, cc_obj.chol.oo, amp[0])
    res +=     0.500000 * einsum('Pai,Pbc,cj->abij'  , cc_obj.chol.vo, cc_obj.chol.vv, amp[0])
    res +=     0.500000 * einsum('Paj,Pki,bk->abij'  , cc_obj.chol.vo, cc_obj.chol.oo, amp[0])
    res +=    -0.500000 * einsum('Paj,Pbc,ci->abij'  , cc_obj.chol.vo, cc_obj.chol.vv, amp[0])
    res +=    -0.500000 * einsum('Pac,Pbi,cj->abij'  , cc_obj.chol.vv, cc_obj.chol.vo, amp[0])
    res +=     0.500000 * einsum('Pac,Pbj,ci->abij'  , cc_obj.chol.vv, cc_obj.chol.vo, amp[0])
    res +=     0.500000 * einsum('Pbi,Pkj,ak->abij'  , cc_obj.chol.vo, cc_obj.chol.oo, amp[0])
    res +=    -0.500000 * einsum('Pbi,Pac,cj->abij'  , cc_obj.chol.vo, cc_obj.chol.vv, amp[0])
    res +=    -0.500000 * einsum('Pbj,Pki,ak->abij'  , cc_obj.chol.vo, cc_obj.chol.oo, amp[0])
    res +=     0.500000 * einsum('Pbj,Pac,ci->abij'  , cc_obj.chol.vo, cc_obj.chol.vv, amp[0])
    res +=     0.500000 * einsum('Pbc,Pai,cj->abij'  , cc_obj.chol.vv, cc_obj.chol.vo, amp[0])
    res +=    -0.500000 * einsum('Pbc,Paj,ci->abij'  , cc_obj.chol.vv, cc_obj.chol.vo, amp[0])
    res +=     0.500000 * einsum('Pki,Plj,balk->abij', cc_obj.chol.oo, cc_obj.chol.oo, amp[1])
    res +=     0.500000 * einsum('Pki,Pac,bckj->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[1])
    res +=    -0.500000 * einsum('Pki,Pbc,ackj->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[1])
    res +=    -0.500000 * einsum('Pkj,Pli,balk->abij', cc_obj.chol.oo, cc_obj.chol.oo, amp[1])
    res +=    -0.500000 * einsum('Pkj,Pac,bcki->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[1])
    res +=     0.500000 * einsum('Pkj,Pbc,acki->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[1])
    res +=    -0.500000 * einsum('Pkc,Pai,bckj->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[1])
    res +=     0.500000 * einsum('Pkc,Paj,bcki->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[1])
    res +=     0.500000 * einsum('Pkc,Pbi,ackj->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[1])
    res +=    -0.500000 * einsum('Pkc,Pbj,acki->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[1])
    res +=    -0.500000 * einsum('Pai,Pkc,bckj->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[1])
    res +=     0.500000 * einsum('Paj,Pkc,bcki->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[1])
    res +=     0.500000 * einsum('Pac,Pki,bckj->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[1])
    res +=    -0.500000 * einsum('Pac,Pkj,bcki->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[1])
    res +=     0.500000 * einsum('Pac,Pbd,dcji->abij', cc_obj.chol.vv, cc_obj.chol.vv, amp[1])
    res +=     0.500000 * einsum('Pbi,Pkc,ackj->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[1])
    res +=    -0.500000 * einsum('Pbj,Pkc,acki->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[1])
    res +=    -0.500000 * einsum('Pbc,Pki,ackj->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[1])
    res +=     0.500000 * einsum('Pbc,Pkj,acki->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[1])
    res +=    -0.500000 * einsum('Pbc,Pad,dcji->abij', cc_obj.chol.vv, cc_obj.chol.vv, amp[1])

    # ih = 2, ibra = 2, len(tmp.terms) = 101
    res +=    -1.000000 * einsum('kc,ak,bcji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,bk,acji->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=     1.000000 * einsum('kc,ci,bakj->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -1.000000 * einsum('kc,cj,baki->abij'  , cc_obj.h1e.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pki,Plj,bk,al->abij', cc_obj.chol.oo, cc_obj.chol.oo, amp[0], amp[0])
    res +=     0.500000 * einsum('Pki,Plj,bl,ak->abij', cc_obj.chol.oo, cc_obj.chol.oo, amp[0], amp[0])
    res +=     0.500000 * einsum('Pki,Pac,cj,bk->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pki,Pbc,cj,ak->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pkj,Pli,bk,al->abij', cc_obj.chol.oo, cc_obj.chol.oo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkj,Pli,bl,ak->abij', cc_obj.chol.oo, cc_obj.chol.oo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkj,Pac,ci,bk->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pkj,Pbc,ci,ak->abij', cc_obj.chol.oo, cc_obj.chol.vv, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Pai,cj,bk->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Paj,ci,bk->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pbi,cj,ak->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Pbj,ci,ak->abij', cc_obj.chol.ov, cc_obj.chol.vo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pai,Pkc,cj,bk->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[0], amp[0])
    res +=     0.500000 * einsum('Paj,Pkc,ci,bk->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[0], amp[0])
    res +=     0.500000 * einsum('Pac,Pki,cj,bk->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pac,Pkj,ci,bk->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[0], amp[0])
    res +=     0.500000 * einsum('Pac,Pbd,ci,dj->abij', cc_obj.chol.vv, cc_obj.chol.vv, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pac,Pbd,di,cj->abij', cc_obj.chol.vv, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pbi,Pkc,cj,ak->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pbj,Pkc,ci,ak->abij', cc_obj.chol.vo, cc_obj.chol.ov, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pbc,Pki,cj,ak->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[0], amp[0])
    res +=     0.500000 * einsum('Pbc,Pkj,ci,ak->abij', cc_obj.chol.vv, cc_obj.chol.oo, amp[0], amp[0])
    res +=    -0.500000 * einsum('Pbc,Pad,ci,dj->abij', cc_obj.chol.vv, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pbc,Pad,di,cj->abij', cc_obj.chol.vv, cc_obj.chol.vv, amp[0], amp[0])
    res +=     0.500000 * einsum('Pki,Plc,ak,bclj->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pki,Plc,al,bckj->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pki,Plc,bk,aclj->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pki,Plc,bl,ackj->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pki,Plc,cj,balk->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pki,Plc,ck,balj->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pki,Plc,cl,bakj->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkj,Plc,ak,bcli->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkj,Plc,al,bcki->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkj,Plc,bk,acli->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkj,Plc,bl,acki->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkj,Plc,ci,balk->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkj,Plc,ck,bali->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkj,Plc,cl,baki->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pli,ak,bclj->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pli,al,bckj->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pli,bk,aclj->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pli,bl,ackj->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pli,cj,balk->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pli,ck,balj->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pli,cl,bakj->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Plj,ak,bcli->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Plj,al,bcki->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Plj,bk,acli->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Plj,bl,acki->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Plj,ci,balk->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Plj,ck,bali->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Plj,cl,baki->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pad,bk,dcji->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pad,ci,bdkj->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pad,cj,bdki->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pad,ck,bdji->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pad,di,bckj->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pad,dj,bcki->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pad,dk,bcji->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pbd,ak,dcji->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pbd,ci,adkj->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pbd,cj,adki->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pbd,ck,adji->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pbd,di,ackj->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pbd,dj,acki->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pbd,dk,acji->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pac,Pkd,bk,dcji->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pac,Pkd,ci,bdkj->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pac,Pkd,cj,bdki->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pac,Pkd,ck,bdji->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pac,Pkd,di,bckj->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pac,Pkd,dj,bcki->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pac,Pkd,dk,bcji->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pbc,Pkd,ak,dcji->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pbc,Pkd,ci,adkj->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pbc,Pkd,cj,adki->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pbc,Pkd,ck,adji->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pbc,Pkd,di,ackj->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=     0.500000 * einsum('Pbc,Pkd,dj,acki->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pbc,Pkd,dk,acji->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,acji,bdlk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,acki,bdlj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,acli,bdkj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,adji,bclk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,adki,bclj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,adli,bckj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,baki,dclj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bali,dckj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bcji,adlk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,bcki,adlj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bcli,adkj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,bdji,aclk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bdki,aclj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,bdli,ackj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,dcji,balk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,dcki,balj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,dcli,bakj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[1], amp[1])

    # ih = 3, ibra = 2, len(tmp.terms) = 52
    res +=    -0.500000 * einsum('Pki,Plc,cj,bk,al->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pki,Plc,cj,bl,ak->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkj,Plc,ci,bk,al->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkj,Plc,ci,bl,ak->abij', cc_obj.chol.oo, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pli,cj,bk,al->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Pli,cj,bl,ak->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Plj,ci,bk,al->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Plj,ci,bl,ak->abij', cc_obj.chol.ov, cc_obj.chol.oo, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pad,ci,dj,bk->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Pad,di,cj,bk->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Pbd,ci,dj,ak->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pbd,di,cj,ak->abij', cc_obj.chol.ov, cc_obj.chol.vv, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pac,Pkd,ci,dj,bk->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pac,Pkd,di,cj,bk->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pbc,Pkd,ci,dj,ak->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pbc,Pkd,di,cj,ak->abij', cc_obj.chol.vv, cc_obj.chol.ov, amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pld,ak,cl,bdji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,ak,dl,bcji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,al,ck,bdji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,al,dk,bcji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,bk,al,dcji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,bk,cl,adji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bk,dl,acji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bl,ak,dcji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,bl,ck,adji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,bl,dk,acji->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,ci,ak,bdlj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,ci,al,bdkj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,ci,bk,adlj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,ci,bl,adkj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,ci,dj,balk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,ci,dk,balj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,ci,dl,bakj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,cj,ak,bdli->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,cj,al,bdki->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,cj,bk,adli->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,cj,bl,adki->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,cj,dk,bali->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,cj,dl,baki->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,di,ak,bclj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,di,al,bckj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,di,bk,aclj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,di,bl,ackj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,di,cj,balk->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,di,ck,balj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,di,cl,bakj->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,dj,ak,bcli->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,dj,al,bcki->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,dj,bk,acli->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,dj,bl,acki->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=    -0.500000 * einsum('Pkc,Pld,dj,ck,bali->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])
    res +=     0.500000 * einsum('Pkc,Pld,dj,cl,baki->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[1])

    # ih = 4, ibra = 2, len(tmp.terms) = 4
    res +=    -0.500000 * einsum('Pkc,Pld,ci,dj,bk,al->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pld,ci,dj,bl,ak->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0], amp[0])
    res +=     0.500000 * einsum('Pkc,Pld,di,cj,bk,al->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0], amp[0])
    res +=    -0.500000 * einsum('Pkc,Pld,di,cj,bl,ak->abij', cc_obj.chol.ov, cc_obj.chol.ov, amp[0], amp[0], amp[0], amp[0])

    return res