import numpy, functools
einsum = functools.partial(numpy.einsum, optimize=True)

def exp_nb_2(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-31 13:31:58
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   c9c553b4876afb61c55774be676e1b9388fb6408

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    return res
