import numpy, functools
einsum = functools.partial(numpy.einsum, optimize=True)

def exp_nb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:35:29
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,J->IJ'           , lam[1], amp[1])
    res +=     1.000000 * einsum('IJ,JK->IK'         , lam[3], amp[3])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , lam[2], amp[2])
    res +=     1.000000 * einsum('IJia,JKai->IK'     , lam[4], amp[4])
    return res

def exp_na_vo(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:35:41
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia->ia'            , lam[0])
    return res

def exp_na_vo_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:36:09
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('Iia->iaI'          , lam[2])
    res +=     1.000000 * einsum('ia,I->iaI'         , lam[0], amp[1])
    res +=     1.000000 * einsum('Iia,IJ->iaJ'       , lam[2], amp[3])
    return res

def exp_na_ov(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:36:21
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,Iai->ai'         , lam[1], amp[2])
    res +=     0.500000 * einsum('IJ,IJai->ai'       , lam[3], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj->bj'      , lam[0], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,Ibi->bj'    , lam[2], amp[0], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,Iaj->bj'    , lam[2], amp[0], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,IJbi->bj'  , lam[4], amp[0], amp[4])
    res +=    -0.500000 * einsum('IJia,bi,IJaj->bj'  , lam[4], amp[0], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,Jaj->bj'  , lam[4], amp[2], amp[2])
    return res

def exp_na_ov_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:36:54
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ai->aiI'         , lam[1], amp[0])
    res +=     1.000000 * einsum('I,IJai->aiJ'       , lam[1], amp[4])
    res +=     1.000000 * einsum('IJ,Jai->aiI'       , lam[3], amp[2])
    res +=     1.000000 * einsum('I,J,Iai->aiJ'      , lam[1], amp[1], amp[2])
    res +=     1.000000 * einsum('I,ai,IJ->aiJ'      , lam[1], amp[0], amp[3])
    res +=    -1.000000 * einsum('ia,aj,Ibi->bjI'    , lam[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('ia,bi,Iaj->bjI'    , lam[0], amp[0], amp[2])
    res +=     1.000000 * einsum('ia,bj,Iai->bjI'    , lam[0], amp[0], amp[2])
    res +=     0.500000 * einsum('IJ,K,IJai->aiK'    , lam[3], amp[1], amp[4])
    res +=     1.000000 * einsum('IJ,Iai,JK->aiK'    , lam[3], amp[2], amp[3])
    res +=    -1.000000 * einsum('Iia,bi,aj->bjI'    , lam[2], amp[0], amp[0])
    res +=    -1.000000 * einsum('Iia,aj,IJbi->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,bi,IJaj->bjJ'  , lam[2], amp[0], amp[4])
    res +=     1.000000 * einsum('Iia,bj,IJai->bjJ'  , lam[2], amp[0], amp[4])
    res +=    -1.000000 * einsum('Iia,Iaj,Jbi->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('Iia,Ibi,Jaj->bjJ'  , lam[2], amp[2], amp[2])
    res +=     1.000000 * einsum('Iia,Ibj,Jai->bjJ'  , lam[2], amp[2], amp[2])
    res +=    -1.000000 * einsum('IJia,aj,Jbi->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,bi,Jaj->bjI'  , lam[4], amp[0], amp[2])
    res +=    -1.000000 * einsum('IJia,Iaj,JKbi->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Ibi,JKaj->bjK', lam[4], amp[2], amp[4])
    res +=     1.000000 * einsum('IJia,Ibj,JKai->bjK', lam[4], amp[2], amp[4])
    res +=     0.500000 * einsum('IJia,Kai,IJbj->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kaj,IJbi->bjK', lam[4], amp[2], amp[4])
    res +=    -0.500000 * einsum('IJia,Kbi,IJaj->bjK', lam[4], amp[2], amp[4])
    res +=    -1.000000 * einsum('ia,bi,aj,I->bjI'   , lam[0], amp[0], amp[0], amp[1])
    res +=    -1.000000 * einsum('Iia,aj,J,Ibi->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,J,Iaj->bjJ' , lam[2], amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,bi,aj,IJ->bjJ' , lam[2], amp[0], amp[0], amp[3])
    res +=    -1.000000 * einsum('IJia,K,Ibi,Jaj->bjK', lam[4], amp[1], amp[2], amp[2])
    res +=    -0.500000 * einsum('IJia,aj,K,IJbi->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,aj,Ibi,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    res +=    -0.500000 * einsum('IJia,bi,K,IJaj->bjK', lam[4], amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,bi,Iaj,JK->bjK', lam[4], amp[0], amp[2], amp[3])
    return res

def exp_na_oo(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:37:06
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =    -1.000000 * einsum('ia,aj->ij'         , lam[0], amp[0])
    res +=    -1.000000 * einsum('Iia,Iaj->ij'       , lam[2], amp[2])
    res +=    -0.500000 * einsum('IJia,IJaj->ij'     , lam[4], amp[4])
    return res

def exp_na_oo_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:37:35
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('I,ji->ijI'         , lam[1], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,Iaj->ijI'       , lam[0], amp[2])
    res +=    -1.000000 * einsum('Iia,aj->ijI'       , lam[2], amp[0])
    res +=    -1.000000 * einsum('Iia,IJaj->ijJ'     , lam[2], amp[4])
    res +=    -1.000000 * einsum('IJia,Jaj->ijI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('I,IJ,ji->ijJ'      , lam[1], amp[3], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('ia,aj,I->ijI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('ia,Iai,kj->jkI'    , lam[0], amp[2], cc_obj.delta.oo)
    res +=    -1.000000 * einsum('Iia,J,Iaj->ijJ'    , lam[2], amp[1], amp[2])
    res +=    -1.000000 * einsum('Iia,aj,IJ->ijJ'    , lam[2], amp[0], amp[3])
    res +=     1.000000 * einsum('Iia,IJai,kj->jkJ'  , lam[2], amp[4], cc_obj.delta.oo)
    res +=    -0.500000 * einsum('IJia,K,IJaj->ijK'  , lam[4], amp[1], amp[4])
    res +=    -1.000000 * einsum('IJia,Iaj,JK->ijK'  , lam[4], amp[2], amp[3])
    return res

def exp_na_vv(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:37:47
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,bi->ba'         , lam[0], amp[0])
    res +=     1.000000 * einsum('Iia,Ibi->ba'       , lam[2], amp[2])
    res +=     0.500000 * einsum('IJia,IJbi->ba'     , lam[4], amp[4])
    return res

def exp_na_vv_xb(cc_obj=None, amp=None, lam=None):
    """
    Generated by gen-cceqs.py at 2023-10-30 14:38:14
    Machine Info: Darwin 23.0.0
    Hostname:     Junjies-MacBook-Air.local
    Git Branch:   pauling
    Git Commit:   8cb28edc0495d8475dffa0df6dc54906513af3bd

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    lam[0]: a+_o a_v
    lam[1]: b
    lam[2]: b a+_o a_v
    lam[3]: b b
    lam[4]: b b a+_o a_v

    """
    res  =     1.000000 * einsum('ia,Ibi->baI'       , lam[0], amp[2])
    res +=     1.000000 * einsum('Iia,bi->baI'       , lam[2], amp[0])
    res +=     1.000000 * einsum('Iia,IJbi->baJ'     , lam[2], amp[4])
    res +=     1.000000 * einsum('IJia,Jbi->baI'     , lam[4], amp[2])
    res +=     1.000000 * einsum('ia,bi,I->baI'      , lam[0], amp[0], amp[1])
    res +=     1.000000 * einsum('Iia,J,Ibi->baJ'    , lam[2], amp[1], amp[2])
    res +=     1.000000 * einsum('Iia,bi,IJ->baJ'    , lam[2], amp[0], amp[3])
    res +=     0.500000 * einsum('IJia,K,IJbi->baK'  , lam[4], amp[1], amp[4])
    res +=     1.000000 * einsum('IJia,Ibi,JK->baK'  , lam[4], amp[2], amp[3])
    return res
