import numpy, functools
einsum = functools.partial(numpy.einsum, optimize=True)

def res_0(cc_obj, amp):
    """
    Generated by gen-cceqs.py at 2023-09-20 13:09:12
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   323903bb20c46a422c99b2415498f89681509a89

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    res   :  a+_o a_v

    ih = 0, ibra = 0, len(tmp.terms) = 1
    ih = 1, ibra = 0, len(tmp.terms) = 7
    ih = 2, ibra = 0, len(tmp.terms) = 8
    ih = 3, ibra = 0, len(tmp.terms) = 2
    ih = 4, ibra = 0, len(tmp.terms) = 0
    """
    res  =     1.000000 * einsum('ai->ai'            , cc_obj.h1e.vo)
    res +=     1.000000 * einsum('I,Iai->ai'         , cc_obj.h1p_eff, amp[2])
    res +=    -1.000000 * einsum('ji,aj->ai'         , cc_obj.h1e.oo, amp[0])
    res +=     1.000000 * einsum('ab,bi->ai'         , cc_obj.h1e.vv, amp[0])
    res +=     1.000000 * einsum('Iai,I->ai'         , cc_obj.h1p1e.vo, amp[1])
    res +=    -1.000000 * einsum('Iji,Iaj->ai'       , cc_obj.h1p1e.oo, amp[2])
    res +=     1.000000 * einsum('Iab,Ibi->ai'       , cc_obj.h1p1e.vv, amp[2])
    res +=    -1.000000 * einsum('jaib,bj->ai'       , cc_obj.h2e.ovov, amp[0])
    res +=    -1.000000 * einsum('jb,bi,aj->ai'      , cc_obj.h1e.ov, amp[0], amp[0])
    res +=    -1.000000 * einsum('Iji,aj,I->ai'      , cc_obj.h1p1e.oo, amp[0], amp[1])
    res +=     1.000000 * einsum('Iab,bi,I->ai'      , cc_obj.h1p1e.vv, amp[0], amp[1])
    res +=    -1.000000 * einsum('Ijb,aj,Ibi->ai'    , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('Ijb,bi,Iaj->ai'    , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=     1.000000 * einsum('Ijb,bj,Iai->ai'    , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('jkib,aj,bk->ai'    , cc_obj.h2e.ooov, amp[0], amp[0])
    res +=     1.000000 * einsum('jabc,ci,bj->ai'    , cc_obj.h2e.ovvv, amp[0], amp[0])
    res +=    -1.000000 * einsum('Ijb,bi,aj,I->ai'   , cc_obj.h1p1e.ov, amp[0], amp[0], amp[1])
    res +=     1.000000 * einsum('jkbc,ci,aj,bk->ai' , cc_obj.h2e.oovv, amp[0], amp[0], amp[0])
    return res

def res_1(cc_obj, amp):
    """
    Generated by gen-cceqs.py at 2023-09-20 13:10:25
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   323903bb20c46a422c99b2415498f89681509a89

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    res   :  b

    ih = 0, ibra = 1, len(tmp.terms) = 1
    ih = 1, ibra = 1, len(tmp.terms) = 5
    ih = 2, ibra = 1, len(tmp.terms) = 3
    ih = 3, ibra = 1, len(tmp.terms) = 0
    """
    res  =     1.000000 * einsum('I->I'              , cc_obj.h1p_eff)
    res +=     1.000000 * einsum('J,IJ->I'           , cc_obj.h1p_eff, amp[3])
    res +=     1.000000 * einsum('IJ,J->I'           , cc_obj.h1p, amp[1])
    res +=     1.000000 * einsum('ia,Iai->I'         , cc_obj.h1e.ov, amp[2])
    res +=     1.000000 * einsum('Iia,ai->I'         , cc_obj.h1p1e.ov, amp[0])
    res +=     1.000000 * einsum('Jia,IJai->I'       , cc_obj.h1p1e.ov, amp[4])
    res +=     1.000000 * einsum('Jia,J,Iai->I'      , cc_obj.h1p1e.ov, amp[1], amp[2])
    res +=     1.000000 * einsum('Jia,ai,IJ->I'      , cc_obj.h1p1e.ov, amp[0], amp[3])
    res +=    -1.000000 * einsum('ijab,bi,Iaj->I'    , cc_obj.h2e.oovv, amp[0], amp[2])
    return res

def res_2(cc_obj, amp):
    """
    Generated by gen-cceqs.py at 2023-09-20 13:10:38
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   323903bb20c46a422c99b2415498f89681509a89

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    res   :  b a+_o a_v

    ih = 0, ibra = 2, len(tmp.terms) = 1
    ih = 1, ibra = 2, len(tmp.terms) = 10
    ih = 2, ibra = 2, len(tmp.terms) = 17
    ih = 3, ibra = 2, len(tmp.terms) = 6
    ih = 4, ibra = 2, len(tmp.terms) = 0
    """
    res  =     1.000000 * einsum('Iai->Iai'          , cc_obj.h1p1e.vo)
    res +=     1.000000 * einsum('J,IJai->Iai'       , cc_obj.h1p_eff, amp[4])
    res +=    -1.000000 * einsum('ji,Iaj->Iai'       , cc_obj.h1e.oo, amp[2])
    res +=     1.000000 * einsum('ab,Ibi->Iai'       , cc_obj.h1e.vv, amp[2])
    res +=     1.000000 * einsum('IJ,Jai->Iai'       , cc_obj.h1p, amp[2])
    res +=    -1.000000 * einsum('Iji,aj->Iai'       , cc_obj.h1p1e.oo, amp[0])
    res +=     1.000000 * einsum('Iab,bi->Iai'       , cc_obj.h1p1e.vv, amp[0])
    res +=     1.000000 * einsum('Jai,IJ->Iai'       , cc_obj.h1p1e.vo, amp[3])
    res +=    -1.000000 * einsum('Jji,IJaj->Iai'     , cc_obj.h1p1e.oo, amp[4])
    res +=     1.000000 * einsum('Jab,IJbi->Iai'     , cc_obj.h1p1e.vv, amp[4])
    res +=    -1.000000 * einsum('jaib,Ibj->Iai'     , cc_obj.h2e.ovov, amp[2])
    res +=    -1.000000 * einsum('jb,aj,Ibi->Iai'    , cc_obj.h1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('jb,bi,Iaj->Iai'    , cc_obj.h1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('Ijb,bi,aj->Iai'    , cc_obj.h1p1e.ov, amp[0], amp[0])
    res +=    -1.000000 * einsum('Jji,J,Iaj->Iai'    , cc_obj.h1p1e.oo, amp[1], amp[2])
    res +=    -1.000000 * einsum('Jji,aj,IJ->Iai'    , cc_obj.h1p1e.oo, amp[0], amp[3])
    res +=     1.000000 * einsum('Jab,J,Ibi->Iai'    , cc_obj.h1p1e.vv, amp[1], amp[2])
    res +=     1.000000 * einsum('Jab,bi,IJ->Iai'    , cc_obj.h1p1e.vv, amp[0], amp[3])
    res +=    -1.000000 * einsum('Jjb,aj,IJbi->Iai'  , cc_obj.h1p1e.ov, amp[0], amp[4])
    res +=    -1.000000 * einsum('Jjb,bi,IJaj->Iai'  , cc_obj.h1p1e.ov, amp[0], amp[4])
    res +=     1.000000 * einsum('Jjb,bj,IJai->Iai'  , cc_obj.h1p1e.ov, amp[0], amp[4])
    res +=    -1.000000 * einsum('Jjb,Iaj,Jbi->Iai'  , cc_obj.h1p1e.ov, amp[2], amp[2])
    res +=    -1.000000 * einsum('Jjb,Ibi,Jaj->Iai'  , cc_obj.h1p1e.ov, amp[2], amp[2])
    res +=     1.000000 * einsum('Jjb,Ibj,Jai->Iai'  , cc_obj.h1p1e.ov, amp[2], amp[2])
    res +=    -1.000000 * einsum('jkib,aj,Ibk->Iai'  , cc_obj.h2e.ooov, amp[0], amp[2])
    res +=     1.000000 * einsum('jkib,bj,Iak->Iai'  , cc_obj.h2e.ooov, amp[0], amp[2])
    res +=     1.000000 * einsum('jabc,ci,Ibj->Iai'  , cc_obj.h2e.ovvv, amp[0], amp[2])
    res +=    -1.000000 * einsum('jabc,cj,Ibi->Iai'  , cc_obj.h2e.ovvv, amp[0], amp[2])
    res +=    -1.000000 * einsum('Jjb,aj,J,Ibi->Iai' , cc_obj.h1p1e.ov, amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Jjb,bi,J,Iaj->Iai' , cc_obj.h1p1e.ov, amp[0], amp[1], amp[2])
    res +=    -1.000000 * einsum('Jjb,bi,aj,IJ->Iai' , cc_obj.h1p1e.ov, amp[0], amp[0], amp[3])
    res +=    -1.000000 * einsum('jkbc,aj,ck,Ibi->Iai', cc_obj.h2e.oovv, amp[0], amp[0], amp[2])
    res +=     1.000000 * einsum('jkbc,ci,aj,Ibk->Iai', cc_obj.h2e.oovv, amp[0], amp[0], amp[2])
    res +=    -1.000000 * einsum('jkbc,ci,bj,Iak->Iai', cc_obj.h2e.oovv, amp[0], amp[0], amp[2])
    return res

def res_3(cc_obj, amp):
    """
    Generated by gen-cceqs.py at 2023-09-20 13:12:32
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   323903bb20c46a422c99b2415498f89681509a89

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    res   :  b b

    ih = 0, ibra = 3, len(tmp.terms) = 0
    ih = 1, ibra = 3, len(tmp.terms) = 5
    ih = 2, ibra = 3, len(tmp.terms) = 5
    ih = 3, ibra = 3, len(tmp.terms) = 0
    """
    res  =     1.000000 * einsum('IK,JK->IJ'         , cc_obj.h1p, amp[3])
    res +=     1.000000 * einsum('JK,IK->IJ'         , cc_obj.h1p, amp[3])
    res +=     1.000000 * einsum('ia,IJai->IJ'       , cc_obj.h1e.ov, amp[4])
    res +=     1.000000 * einsum('Iia,Jai->IJ'       , cc_obj.h1p1e.ov, amp[2])
    res +=     1.000000 * einsum('Jia,Iai->IJ'       , cc_obj.h1p1e.ov, amp[2])
    res +=     1.000000 * einsum('Kia,K,IJai->IJ'    , cc_obj.h1p1e.ov, amp[1], amp[4])
    res +=     1.000000 * einsum('Kia,Iai,JK->IJ'    , cc_obj.h1p1e.ov, amp[2], amp[3])
    res +=     1.000000 * einsum('Kia,Jai,IK->IJ'    , cc_obj.h1p1e.ov, amp[2], amp[3])
    res +=    -1.000000 * einsum('ijab,bi,IJaj->IJ'  , cc_obj.h2e.oovv, amp[0], amp[4])
    res +=    -1.000000 * einsum('ijab,Ibi,Jaj->IJ'  , cc_obj.h2e.oovv, amp[2], amp[2])
    return res

def res_4(cc_obj, amp):
    """
    Generated by gen-cceqs.py at 2023-09-20 13:12:36
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   323903bb20c46a422c99b2415498f89681509a89

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o
    res   :  b b a+_o a_v

    ih = 0, ibra = 4, len(tmp.terms) = 0
    ih = 1, ibra = 4, len(tmp.terms) = 9
    ih = 2, ibra = 4, len(tmp.terms) = 31
    ih = 3, ibra = 4, len(tmp.terms) = 17
    ih = 4, ibra = 4, len(tmp.terms) = 0
    """
    res  =    -1.000000 * einsum('ji,IJaj->IJai'     , cc_obj.h1e.oo, amp[4])
    res +=     1.000000 * einsum('ab,IJbi->IJai'     , cc_obj.h1e.vv, amp[4])
    res +=     1.000000 * einsum('IK,JKai->IJai'     , cc_obj.h1p, amp[4])
    res +=     1.000000 * einsum('JK,IKai->IJai'     , cc_obj.h1p, amp[4])
    res +=    -1.000000 * einsum('Iji,Jaj->IJai'     , cc_obj.h1p1e.oo, amp[2])
    res +=     1.000000 * einsum('Iab,Jbi->IJai'     , cc_obj.h1p1e.vv, amp[2])
    res +=    -1.000000 * einsum('Jji,Iaj->IJai'     , cc_obj.h1p1e.oo, amp[2])
    res +=     1.000000 * einsum('Jab,Ibi->IJai'     , cc_obj.h1p1e.vv, amp[2])
    res +=    -1.000000 * einsum('jaib,IJbj->IJai'   , cc_obj.h2e.ovov, amp[4])
    res +=    -1.000000 * einsum('jb,aj,IJbi->IJai'  , cc_obj.h1e.ov, amp[0], amp[4])
    res +=    -1.000000 * einsum('jb,bi,IJaj->IJai'  , cc_obj.h1e.ov, amp[0], amp[4])
    res +=    -1.000000 * einsum('jb,Iaj,Jbi->IJai'  , cc_obj.h1e.ov, amp[2], amp[2])
    res +=    -1.000000 * einsum('jb,Ibi,Jaj->IJai'  , cc_obj.h1e.ov, amp[2], amp[2])
    res +=    -1.000000 * einsum('Ijb,aj,Jbi->IJai'  , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('Ijb,bi,Jaj->IJai'  , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('Jjb,aj,Ibi->IJai'  , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('Jjb,bi,Iaj->IJai'  , cc_obj.h1p1e.ov, amp[0], amp[2])
    res +=    -1.000000 * einsum('Kji,K,IJaj->IJai'  , cc_obj.h1p1e.oo, amp[1], amp[4])
    res +=    -1.000000 * einsum('Kji,Iaj,JK->IJai'  , cc_obj.h1p1e.oo, amp[2], amp[3])
    res +=    -1.000000 * einsum('Kji,Jaj,IK->IJai'  , cc_obj.h1p1e.oo, amp[2], amp[3])
    res +=     1.000000 * einsum('Kab,K,IJbi->IJai'  , cc_obj.h1p1e.vv, amp[1], amp[4])
    res +=     1.000000 * einsum('Kab,Ibi,JK->IJai'  , cc_obj.h1p1e.vv, amp[2], amp[3])
    res +=     1.000000 * einsum('Kab,Jbi,IK->IJai'  , cc_obj.h1p1e.vv, amp[2], amp[3])
    res +=    -1.000000 * einsum('Kjb,Iaj,JKbi->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=    -1.000000 * einsum('Kjb,Ibi,JKaj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=     1.000000 * einsum('Kjb,Ibj,JKai->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=    -1.000000 * einsum('Kjb,Jaj,IKbi->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=    -1.000000 * einsum('Kjb,Jbi,IKaj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=     1.000000 * einsum('Kjb,Jbj,IKai->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=     1.000000 * einsum('Kjb,Kai,IJbj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=    -1.000000 * einsum('Kjb,Kaj,IJbi->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=    -1.000000 * einsum('Kjb,Kbi,IJaj->IJai', cc_obj.h1p1e.ov, amp[2], amp[4])
    res +=    -1.000000 * einsum('jkib,aj,IJbk->IJai', cc_obj.h2e.ooov, amp[0], amp[4])
    res +=     1.000000 * einsum('jkib,bj,IJak->IJai', cc_obj.h2e.ooov, amp[0], amp[4])
    res +=    -1.000000 * einsum('jkib,Iaj,Jbk->IJai', cc_obj.h2e.ooov, amp[2], amp[2])
    res +=     1.000000 * einsum('jkib,Ibj,Jak->IJai', cc_obj.h2e.ooov, amp[2], amp[2])
    res +=     1.000000 * einsum('jabc,ci,IJbj->IJai', cc_obj.h2e.ovvv, amp[0], amp[4])
    res +=    -1.000000 * einsum('jabc,cj,IJbi->IJai', cc_obj.h2e.ovvv, amp[0], amp[4])
    res +=     1.000000 * einsum('jabc,Ici,Jbj->IJai', cc_obj.h2e.ovvv, amp[2], amp[2])
    res +=    -1.000000 * einsum('jabc,Icj,Jbi->IJai', cc_obj.h2e.ovvv, amp[2], amp[2])
    res +=    -1.000000 * einsum('Kjb,K,Iaj,Jbi->IJai', cc_obj.h1p1e.ov, amp[1], amp[2], amp[2])
    res +=    -1.000000 * einsum('Kjb,K,Ibi,Jaj->IJai', cc_obj.h1p1e.ov, amp[1], amp[2], amp[2])
    res +=    -1.000000 * einsum('Kjb,aj,K,IJbi->IJai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('Kjb,aj,Ibi,JK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res +=    -1.000000 * einsum('Kjb,aj,Jbi,IK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res +=    -1.000000 * einsum('Kjb,bi,K,IJaj->IJai', cc_obj.h1p1e.ov, amp[0], amp[1], amp[4])
    res +=    -1.000000 * einsum('Kjb,bi,Iaj,JK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res +=    -1.000000 * einsum('Kjb,bi,Jaj,IK->IJai', cc_obj.h1p1e.ov, amp[0], amp[2], amp[3])
    res +=    -1.000000 * einsum('jkbc,aj,ck,IJbi->IJai', cc_obj.h2e.oovv, amp[0], amp[0], amp[4])
    res +=     1.000000 * einsum('jkbc,aj,Ici,Jbk->IJai', cc_obj.h2e.oovv, amp[0], amp[2], amp[2])
    res +=    -1.000000 * einsum('jkbc,aj,Ick,Jbi->IJai', cc_obj.h2e.oovv, amp[0], amp[2], amp[2])
    res +=     1.000000 * einsum('jkbc,ci,aj,IJbk->IJai', cc_obj.h2e.oovv, amp[0], amp[0], amp[4])
    res +=    -1.000000 * einsum('jkbc,ci,bj,IJak->IJai', cc_obj.h2e.oovv, amp[0], amp[0], amp[4])
    res +=     1.000000 * einsum('jkbc,ci,Iaj,Jbk->IJai', cc_obj.h2e.oovv, amp[0], amp[2], amp[2])
    res +=    -1.000000 * einsum('jkbc,ci,Ibj,Jak->IJai', cc_obj.h2e.oovv, amp[0], amp[2], amp[2])
    res +=     1.000000 * einsum('jkbc,cj,Iak,Jbi->IJai', cc_obj.h2e.oovv, amp[0], amp[2], amp[2])
    res +=     1.000000 * einsum('jkbc,cj,Ibi,Jak->IJai', cc_obj.h2e.oovv, amp[0], amp[2], amp[2])
    return res

def ene(cc_obj, amp):
    """
    Generated by gen-cceqs.py at 2023-09-20 13:16:52
    Machine Info: Linux 3.10.0-327.36.3.el7.x86_64
    Hostname:     pauling001
    Git Branch:   pauling
    Git Commit:   323903bb20c46a422c99b2415498f89681509a89

    amp[0]: a+_v a_o
    amp[1]: b+
    amp[2]: b+ a+_v a_o
    amp[3]: b+ b+
    amp[4]: b+ b+ a+_v a_o

    ih = 0, ibra = 5, len(tmp.terms) = 0
    ih = 1, ibra = 5, len(tmp.terms) = 3
    ih = 2, ibra = 5, len(tmp.terms) = 2
    ih = 3, ibra = 5, len(tmp.terms) = 0
    """
    res  =     1.000000 * einsum('I,I->'             , cc_obj.h1p_eff, amp[1])
    res +=     1.000000 * einsum('ia,ai->'           , cc_obj.h1e.ov, amp[0])
    res +=     1.000000 * einsum('Iia,Iai->'         , cc_obj.h1p1e.ov, amp[2])
    res +=     1.000000 * einsum('Iia,ai,I->'        , cc_obj.h1p1e.ov, amp[0], amp[1])
    res +=    -0.500000 * einsum('ijab,bi,aj->'      , cc_obj.h2e.oovv, amp[0], amp[0])
    return res
